### ISSUE TITLE
After Upgrade to 1.0.2 local sqlite changes are not uploaded to remote

### ISSUE THREAD

**Issue by ricardoamm** [Mimetis/Dotmim.Sync#1191]
After Upgrade to 1.0.2 local sqlite changes are not uploaded to remote.
The local sqlite file where removed and recreated again, but the behaviour remains.

**Comment by Mimetis** [comment]
Damn
Are you able to provide a sample that reproduces the error ?
What version were you using before upgrading to 1.0.2 ?

**Comment by ricardoamm** [comment]
I was using the version 0.9.8 
I can't provide a sample, because the project is to big.
I even Drop All and provisioning all over again, but did't solve.

**Comment by Mimetis** [comment]
Ok
What is the remote provider ? (**SQL**, **SQL ChangeTracking**, **MySQL**, **PostgreSQL**)
Can you describe your architecture (or share your server/ client code) ?

Some thoughts:

- Make some tests with a new fresh **SQLite** database
- Try to make a simple sync with only one table
- Try to make a simple sync without using an **HTTP** connection, but a real simple **TCP** connection, using a simple `RemoteOrchestrator`
- Try to make a sync based on you architecture, using the `AdventureWorks `database and see if you have the same error
- Try to Deprovision / Provision again the server side (be sure to backup the db before, just in case)

**Comment by VagueGit** [comment]
@ricardoamm you might try upgrading to DMS 1.0.1. We have been running DMS 1.0.0-beta-1517->1.0.1 in production in our app (SQLite-SQL Server via http) since August 2023.

We sync hundreds of SQL Server databases on our server to thousands of SQLite dbs on client machines.

We have been running DMS 1.0.1 in production in our app since 13 June without issue.

We were deterred from releasing DMS 1.0.2 by the very long delay in first sync. DMS 1.0.2 deprovisions and reprovisions the local SQLite db. Then there is a very long delay without apparent progress. Maybe you have found the cause.

**Comment by Mimetis** [comment]
> The WebRemoteOrchestrator version is 1.0.2 I dowgraded the Client Application to 0.9.8 and it worked.

That's weird !
I did not changed a lot of things honestly between these 2 versions
I would love to understand what happens to you ....

If you have anytime to investigate it, let me know

**Comment by ricardoamm** [comment]
Here goes a Client code:

[com.smartthink.sigo.portal.sync.Client.zip](https://github.com/user-attachments/files/15889484/com.smartthink.sigo.portal.sync.Client.zip)

**Comment by Mimetis** [comment]
Thanks, 
I don't see anything strange in your client code (but man, that's a huge sync setup :) )

**Comment by ricardoamm** [comment]
You can run it, the EndPoint is public

**Comment by Mimetis** [comment]
The problem seems to come from your filter, that is way to much complicated for me.

As an example on this one, generated on the fly:

``` sql
SELECT DISTINCT 
	[side].[Oid], 
	[base].[Registo], 
	[base].[DepartamentoTimeSheet], 
	[base].[DataRegisto], 
	[base].[DataAtualizacao], 
	[base].[Funcionario], 
	[base].[Observacoes], 
	[base].[Estado], 
	[base].[Sincroniza], 
	[base].[Anexos], 
	[side].[sync_row_is_tombstone], 
	[side].[update_scope_id] as [sync_update_scope_id] 
FROM [SigoRegistoFaltas_tracking] [side]
LEFT JOIN [SigoRegistoFaltas] [base]
ON [base].[Oid] = [side].[Oid]

LEFT JOIN [ErpFuncionarios] ON [base].[Funcionario] = [ErpFuncionarios].[Codigo]
LEFT JOIN [ErpDepartamentos] ON [ErpFuncionarios].[CodDepartamento] = [ErpDepartamentos].[Departamento]
LEFT JOIN [SigoCentroUtilizadores] ON [ErpDepartamentos].[CDU_Centro] = [SigoCentroUtilizadores].[Centro]
LEFT JOIN [PermissionPolicyUser] ON [SigoCentroUtilizadores].[User] = [PermissionPolicyUser].[Oid]
WHERE 
(
 (
   ([PermissionPolicyUser].[UserName] = @user) AND ([base].[Sincroniza] = @sincronize)
  )
 OR [side].[sync_row_is_tombstone] = 1
)
AND 
([side].[timestamp] > @sync_min_timestamp AND [side].[update_scope_id] IS NULL)
```

You are making a filter in the user (@user)

But if I look at the user, by modifying the query, to get the user, like this:

``` sql
SELECT DISTINCT 
	[side].[Oid], 
	[base].[Registo], 
	[base].[DepartamentoTimeSheet], 
	[base].[DataRegisto], 
	[base].[DataAtualizacao], 
	[base].[Funcionario], 
	[base].[Observacoes], 
	[base].[Estado], 
	[base].[Sincroniza], 
	[base].[Anexos], 
	[side].[sync_row_is_tombstone], 
	[side].[update_scope_id] as [sync_update_scope_id],
	[PermissionPolicyUser].[UserName]
FROM [SigoRegistoFaltas_tracking] [side]
LEFT JOIN [SigoRegistoFaltas] [base]
ON [base].[Oid] = [side].[Oid]

LEFT JOIN [ErpFuncionarios] ON [base].[Funcionario] = [ErpFuncionarios].[Codigo]
LEFT JOIN [ErpDepartamentos] ON [ErpFuncionarios].[CodDepartamento] = [ErpDepartamentos].[Departamento]
LEFT JOIN [SigoCentroUtilizadores] ON [ErpDepartamentos].[CDU_Centro] = [SigoCentroUtilizadores].[Centro]
LEFT JOIN [PermissionPolicyUser] ON [SigoCentroUtilizadores].[User] = [PermissionPolicyUser].[Oid]
```

I don't see any user:

![image](https://github.com/Mimetis/Dotmim.Sync/assets/4592555/b61fce22-bc83-40da-93da-94d33d3f4fff)

Make sense for you ?

**Comment by Mimetis** [comment]
I think I got it

Before `1.0.0`, **SQLite** client was sending everything that changed locally, without applying the filter.
Since `1.0.0`, **SQLite**, like any other provider, is using the filter to get the local rows to send to the server.

That means your filter is applied on the client side, and that's why you don't have any rows sent back to the server.

**Comment by ricardoamm** [comment]
In the real Client Database, I have de @user.

![image](https://github.com/Mimetis/Dotmim.Sync/assets/26299584/57ec2807-8f8f-437a-b0f1-164363235560)

The filter seems ok to me.

**Comment by Mimetis** [comment]
So I can't help you, as I don't have the same behavior / data in the example you provide

**Comment by ricardoamm** [comment]
In the sample I provide, indeed, I have the same behavior. 
What I meant is that in the production environment, the @user in each row is filled, but the changes are not uploaded. 

Could you validate for other entity:

UPDATE SigoDepartamentoTimeSheetMovimentos set Observacoes = 'Test' where Oid = 'C97F32DC-39EF-4720-86FE-071A72540552'

**Comment by Mimetis** [comment]
As I said, now the sqlite is also applying the filter on the client side, so I guess your problem is coming from this.
I'm not sure I can help you more on that
