### ISSUE TITLE
SyncType.Reinitialize Deletes All Table Records Without Considering Filters

### ISSUE THREAD

**Issue by nicolazreinh** [Mimetis/Dotmim.Sync#1223]
When using the `dotmim.sync` library to synchronize a local database with a web orchestrator, I've encountered an issue where invoking `SynchronizeAsync` with `SyncType.Reinitialize` results in the deletion of all table records. This behavior occurs without considering any filters applied to the scope.

#### Steps to Reproduce

1. Set up a sync agent with a filtered scope.
2. Call `await agent.SynchronizeAsync(scopeName, SyncType.Reinitialize)` to synchronize the local database with the cloud.
3. Observe that all records in the tables are deleted, ignoring the scope filters.

#### Expected Behavior

The expected behavior is that the `SynchronizeAsync` method should respect the filters applied to the scope and only delete records that do not meet the filter criteria.

#### Actual Behavior

All records in the tables are deleted regardless of the filters applied to the scope.

#### Code Sample

```csharp
var agent = new SyncAgent(clientProvider, serverProvider, options);

// Define the scope with filters
var scopeName = "filteredScope";
// Synchronize with Reinitialize
await agent.SynchronizeAsync(scopeName, SyncType.Reinitialize);
```

#### Environment

- dotmim.sync version: 1.0.2
- Database provider: SQL Server

**Comment by Mimetis** [comment]
The problem is that `SyncType.Reinitialize` is applying a `Reset` on the client database, where there is no need (for some providers) to filters rows.

I mean, for `SqliteSyncProvider`, there is no filters on client side as we consider that it's not needed. 
For `SqlSyncProvider`, filters are applied on client, but there are a lot of reasons and discussions to disable them and having the same behavior as for **SQLite**. (Same discussions for **MySQL** / **PostgreSQL**)

For now, the Reset command is applying a full drop on the tables, but you can tweak this behavior, using an interceptor, like:

``` cs
agent.LocalOrchestrator.OnExecuteCommand(args =>
{
    if (args.CommandType == DbCommandType.Reset && args.Context.ScopeName == "filteredScope")
    {
        args.Command.CommandText = BuildYourOwnCommandText();
    }
});
```

It's not ideal, but could it be a good option for your use case ?

**Comment by nicolazreinh** [comment]
Thank you for the response! I will try your suggestion. However, I am not sure what the BuildYourOwnCommandText method should be. Can you please provide an example?

**Comment by Mimetis** [comment]
A query that returns all the rows you want to delete.

**Comment by nicolazreinh** [comment]
Great, thank you
