### ISSUE TITLE
Passing table array with more than one table does not work

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#14]
Hi,
I'm trying to run this sync sample. 
It works, when I put only one table in tables-array. But when adding more or all tables of my database, it does not. What am I doing wrong here?

Thanks
Reinhold

[Program.zip](https://github.com/Mimetis/Dotmim.Sync/files/1459257/Program.zip)

**Comment by thefonzi** [comment]
Hello Sèbastian,
here is the complete project. The same problem raises with AdventureWorks.

Reinhold
[SyncsServer.zip](https://github.com/Mimetis/Dotmim.Sync/files/1460255/SyncsServer.zip)

**Comment by thefonzi** [comment]
sorry, I think, this was my fault.

**Comment by Mimetis** [comment]
Hey @thefonzi,

Thx for your feedback. 
I tried your sample on my machine.
First of all, since your code is running a script to know which tables you want to sync, I don't know what tables you have in your sync process.
That's why I've tested with this configuration:

``` sql
var tables = new string[] {"ErrorLog", "ProductCategory",
        "ProductDescription", "ProductModel",
        "Product", "ProductModelProductDescription",
        "Address", "Customer", "CustomerAddress",
        "SalesOrderHeader", "SalesOrderDetail" };

```
Then, you 've made a littme mistake, since you don't call `await` when you launch the sync (method `agent.SynchronizeAsync()` )

Here is the code I've changed on my side:

```
 var s = await agent.SynchronizeAsync()
```

In your sample, we're in a console app, and the `main` method can't be marked as `async` so the final code is 

```
 var s = agent.SynchronizeAsync().GetAwaiter().GetResult();
```
And it worked as expected on my machine.
If it doesn't work after thoses corrections, I will investigate more deeply

Sebastien
