### ISSUE TITLE
Removing Cross Relation makes Sync work

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#16]
Hello Sébastien,
I have done some further tests. 
Removing the Cross-Relation indicated in attached image is enough to make sync work. 
So the double reference of one table to another (XpoState-XpoTransition) seems not to be a problem.
![crossrelation](https://user-images.githubusercontent.com/6755910/32740576-a7cf8d28-c8a3-11e7-8818-81666c1a514f.PNG)

**Comment by thefonzi** [comment]
Hi Sébastien,
i have cleaned up the sample that produces the following error: "Error occured during EnsureConfiguration of type DataStore: Foreign column Oid does not exist in table XpoState".

In the attached sample you find just 2 tables, that refernce each other in different fields. I'm not sure, if this type of reference is possible to replicate. Maybe you can have a look. Otherwise it will be neccesary to remove such FKs from databases that shall be synchronized. 

Regards
Reinhold

[DotminXAF-Relations.zip](https://github.com/Mimetis/Dotmim.Sync/files/1470033/DotminXAF-Relations.zip)

**Comment by Mimetis** [comment]
Yes, I see the problem.
During the code generation, the `Dotmim.Sync` core process generate the tables, if needed.
I shall generate the relations at the end, when all tables are created.
Actually they are create when the table is created, that's why it can't work on this example.

Today:

* Generate Table 1
* Searching Table 1 foreign keys
* Generating Table 2
* Searching Table 2 foreign keys

For the next version, I will:
* Generate Table 1
* Generate Table 2
* Searching Table 1 foreign keys
* Searching Table 2 foreign keys

Eventually, you have another option to be able to sync, even with the circular Relationship:  
Create the client database **with** an initial schema.  
In this case, the `Dotmim.Sync` fx won't create tables and relations, since they are already there.  

Give a try and let me know if it's working !

**Comment by Mimetis** [comment]
Actually, if there is a cross reference, we can't make any bulk insert and so on... Even if I change the table / relations generation script.  
So I made a correction to raise an error if I see a cross reference...
