### ISSUE TITLE
[Enhancement/Question] Differ the sync

### ISSUE THREAD

**Issue by MrKniight** [Mimetis/Dotmim.Sync#174]
In a classic setup with a central database called the Master, getting requests from different clients :
is there a way  to be able to "differ" the sync (maybe with sync configuration parameters but i don't think) ?
As in : get the last changes from the Master server without uploading the new things from the client to the Master.

The idea behind that is to be able to have a kind of "pending" work on the client, and only commit it when the user decides it, BUT the client still need to get "fresh" datas from the Master regularly. The thing is right now, if we "sync" and there's no conflict, everything will be uploaded and downloaded.

As an added (so 2nd) feature to that : while getting the datas from the Master, if there are conflicts, let the client choose "keep mine" or "take server" but still not commit changes immediately to the Master. Right now it is of course possible to intercept conflicts but that would mean "postpone" them and still choose a resolution everytime we would get datas from the Master.

Thanks

**Comment by Mimetis** [comment]
### 1 - Differing datas.

Actually, it's not possible, with the version `0.3`.
In a future version (probably not the version `0.4`, maybe `0.5`) I'm thinking about let the user (from the client perspective) decides from which point in time he wants to sync its data.
So basically in your case, you would be able to sync T0, T1, T2, T4 from the server in a `DownloadOnly` option, and then make a `Bidirectional` sync from T1 to T5.
It's on the roadmap, but be sure, not today or tomorrow, maybe next year :)

### Conflicts

Be careful, all conflicts are resolved on the server side. 
It's always the server who decices which row is the correct one.
I don't think I will bring a feature for postpone conflicts, because, the databases will be then in a "de-synchronized" state.

**Comment by MrKniight** [comment]
yes dont worry the resolution only in server side was very well explained in the how-to.
So
> So basically in your case, you would be able to sync T0, T1, T2, T4 from the server in a DownloadOnly option, and then make a Bidirectional sync from T1 to T5.
does that mean if the download would find conflicts on client, we have to solve them immediately ? or downloadonly doesnt care about conflicts ?

about point 1 : i forgot to add an other question which is related in some way : 
are we able just with the database to find (for extraction) all the changes related to "one sync operation" ? meaning being able to discover what we call the "T0, T1... T5" changes. I only see that being doable by selecting on "update_timestamp" or "last_change_datetime" (at first i thought scope_id was maybe usable but it's not related to that).

but yeah, those enhancements are surely heavy, no doubt about that.

**Comment by Mimetis** [comment]
### find (for extraction) all the changes related to "one sync operation"

No, it's not available "out of the box". It would have been to complicated to manage, and will generate a bunch of data !
By the way, I did not test it yet, but I think you should be able to use an `Interceptor` during the `GetChanges` event (I think on the server side) and save it in a *historical table* I guess ?
