### ISSUE TITLE
version 0.4 - please set the .net core runtime to version 3

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#186]
hosting providers have .net core 3.0 deployed by default. I tried upgrading your project to .net core 3.0 and there are a number of issues.

They could be bugs in R0.4 

to make the transition easier to .net core3.0 maybe you should upgrade and test it for .net core 3.0 to start with.

**Comment by Mimetis** [comment]
All the assemblies are `.net standard 2.0`
It means it works on all platforms that support it, including `.Net Framework 4.8` to `.Net Core 3.1`

Since `.Net Core 3.1` is the **LTS** version, you should consider to upgrade to `.Net Core 3.1`
Meanwhile, `.Net Core 3.0` is supported of course.
For instance, the tests pipeline on Azure Devops are using the `.Net Core 3.0` runtime.
You can see the results of the last tests [here](https://dev.azure.com/dotmim/Dotmim.Sync/_build/results?buildId=250&view=logs&j=9e11e48c-707a-5a5f-a99d-b29c2c089eef&t=2997a1ca-d917-564f-61c7-559eb9422663).

So far, since `v0.4` is not yet released, it subjects to a lot of changes, internally.
So be sure, every time you upgrade the assemblies (at this time I just release [0.4.0-beta-0250](https://www.nuget.org/packages/Dotmim.Sync.SqlServer/0.4.0-beta-0250) you start with a fresh *not already provisioned* database.

Now, if you still have some issues, please submit an issue *per* bug you encountered. I will fix these issues as far as possible :)

Thanks a lot @mdonogma for using this *in progress* framework and make feedbacks !
