### ISSUE TITLE
Some restrictions on filters (especially on Delete statement with a filter)

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#199]
what does this mean?

tracking provider

**Comment by Mimetis** [comment]
Well, there is no way to filter deleted rows for one filtered database
I mean;, when the sync fx make a `GetChanges`:
- it gets all the filtered rows (added, modified) because the row has the filter on the correct column
- it won't have deleted rows, because the only information we had, is the primary key

So far, if a row is deleted, every client will receive the deleted row (just the primary key) and will try to delete it on the local database.
It's not really risky, but some clients will try to delete a row that is not part of their own filter.

**Comment by mdonogma** [comment]
Makes perfect sense. Great work on this!

Sent from my iPhone

On 3 Feb 2020, at 09:09, Sébastien Pertus <notifications@github.com> wrote:

﻿

Well, there is no way to filter deleted rows for one filtered database
I mean;, when the sync fx make a GetChanges:

  *   it gets all the filtered rows (added, modified) because the row has the filter on the correct column
  *   it won't have deleted rows, because the only information we had, is the primary key

So far, if a row is deleted, every client will receive the deleted row (just the primary key) and will try to delete it on the local database.
It's not really risky, but some clients will try to delete a row that is not part of their own filter.
