### ISSUE TITLE
Issue syncing MS Sql table with ntext column

### ISSUE THREAD

**Issue by Demotis** [Mimetis/Dotmim.Sync#214]
I see in the source that ntext and text are allowed column types. Is there a reason that these are not able to sync? Is there a work around, or am I doing something wrong in the sync settings to support these column types?

**Comment by Mimetis** [comment]
Actually, There is a validation step where the `Dotmim.Sync` framework analyzes the column datatypes.

And unfortunatelly, `ntext` and `text` are not allowed.

The reason is quite simple : `ntext` and `text` are not working well with triggers.

Here is the kind of issue you will face, if you pass through the validation:
![image](https://user-images.githubusercontent.com/4592555/74325996-ef5e1480-4d89-11ea-81e0-eb7ed0906162.png)

More from the official documentation:

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15

> ntext, text, and image data types will be removed in a future version of MicrosoftSQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead. Both AFTER and INSTEAD OF triggers support varchar(MAX), nvarchar(MAX), and varbinary(MAX) data in the inserted and deleted tables.
