### ISSUE TITLE
[Bug]Updating to latest NuGet packages: MySqlCommandBuilder removed

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#22]
Hello,
after updating to latest packages, the MySqlCommandBuilder seems to be substituted with a new class.
Can you have a look?

**Comment by Mimetis** [comment]
There was no `MySqlCommandBuilder` in the `MySql` package.

The only builder is actually in the `Sqlite` provider.

Do you believe that a builder is something useful in the providers ?   
I mean, today, only SQLite has one, but we can definitively add for each provider.  

Something like that:

```
public SqliteSyncProvider(SqliteConnectionStringBuilder builder)
```

```
public MySqlServerSyncProvider(MySqlConnectionStringBuilder builder)
```

```
public SqlServerSyncProvider(SqlConnectionStringBuilder builder)
```

Is that make sense ?

**Comment by thefonzi** [comment]
hm,  I get this error in public static class MySqlExtensionsMethods
 try
            {
                MySqlCommandBuilder.DeriveParameters(cmd);
            }
            finally
            {
                if (!alreadyOpened)
                    connection.Close();
            }

**Comment by Mimetis** [comment]
Ok, my bad, it's not the `MySqlConnectionStringBuilder`, it's about `MySqlCommandBuilder` ..   
Will check that !

**Comment by Mimetis** [comment]
Ok, I made some corrections on the MySQL provider in the last commit:
* I change the ADO.NET compatible provider, to be compatible with .NET Standard 2.0
* I made some corrections on the BLOB Generation.

Since the code generation has changed, you should do before testing:  
* Drop your tables `[Table]_tracking`
* Drop all the generated stored procédures
* Drop the `scope_info` table (or at least delete all rows in it)

Let me know if everything is working as expected.
