### ISSUE TITLE
Why not switching from System.Data.SqlClient to Microsoft.Data.SqlClient ?

### ISSUE THREAD

**Issue by jeremy-waguet** [Mimetis/Dotmim.Sync#241]
I only keep using System.Data.SqlClient on my project (closed source) because of using Dotmim.Sync. Is there any reason not to use the new recommended sqlclient ?

Thank you for having developed the missing maintained alternative to the old no more maintained Sync Framework !

Source: https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

**Comment by Mimetis** [comment]
Hello @jeremy-waguet .
Thanks for the feedback !

It's already done in the next version `v0.5` (this version will be shipped by the end of April)

But, if you need it for the version `v0.4`, you can clone the source code and make some references changes:
### `Dotmim.Sync.Core` 
- Nothing to be done on thi project. 
It uses the `System.Data.Common` namespace and it's the base class library for both `Microsoft.Data.SqlClient` and `System.Data.SqlClient`

### `Dotmim.Sync.SqlServer`
- Add nuget package `Microsoft.Data.SqlClient` and remove package `System.Data.SqlClient`
- Find and Replace `using System.Data.SqlClient;` with `using Microsoft.Data.SqlClient;` 
- Find and Replace `using Microsoft.SqlServer.Server;` with `using Microsoft.Data.SqlClient.Server;` 

### `Dotmim.Sync.SqlServer.ChangeTracking`
- Same as previous project project

**Comment by jeremy-waguet** [comment]
Hi,Don't worry I can wait until the next release to be available.On 28 Mar 2020 17:31, Sébastien Pertus <notifications@github.com> wrote:
Hello @jeremy-waguet .
Thanks for the feedback !
It's already done in the next version v0.5 (this version will be shipped by the end of April)
But, if you need it for the version v0.4, you can clone the source code and make some references changes:
Dotmim.Sync.Core
Nothing to be done on thi project.
It uses the System.Data.Common namespace and it's the base class library for both Microsoft.Data.SqlClient and System.Data.SqlClient
Dotmim.Sync.SqlServer
Add nuget package Microsoft.Data.SqlClient and remove package System.Data.SqlClientFind and Replace using System.Data.SqlClient; with using Microsoft.Data.SqlClient;Find and Replace using Microsoft.SqlServer.Server; with using Microsoft.Data.SqlClient.Server;
Dotmim.Sync.SqlServer.ChangeTracking
Same as previous project project

**Comment by Mimetis** [comment]
@jeremy-waguet  The `v0.5` branch is available.

You can test if from nuget. 

https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.0-beta-0299

You can manually install it, through this command line:
``` bash
dotnet add package Dotmim.Sync.Core --version 0.5.0-beta-0299
```

Or through Visual Studio
Be sure to select **Pre-release** to see the packages, inside Visual Studio

![image](https://user-images.githubusercontent.com/4592555/78261943-2e922180-7500-11ea-970c-30a1bc69b528.png)

Or you can directly grab the code from the branch ``Mimetis-v0.5` here : https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5
You will have to clone it locally and rebuild it, to use it.
Rebuild:
- `Dotmim.Sync.Core`
- `Dotmim.Sync.MySql`
- `Dotmim.Sync.Sqlite`
- `Dotmim.Sync.SqlServer`
- `Dotmim.Sync.SqlServer.ChangeTracking`
- `Dotmim.Sync.Web.Client`
- `Dotmim.Sync.Web.Server`

**Be careful, there is some breaking changes, and the doc is not up to date with these changes.**

If you want to test it, be sure to start from a **fresh new server and client databases**, because there is no "upgrade path from `v0.4` to `v0.5`" ... *yet*

If you need some example, do not hesitate to search in:
- Tests projects: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Tests/Dotmim.Sync.Tests 
- Console sample: https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Dotmim.Sync.SampleConsole
- Web Api project: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Samples/Dotmim.Sync.SampleWebServer

If you are testing this version, let me know what you find / need
