### ISSUE TITLE
WebClientOrchestrator() doesnt working for multi scope environment

### ISSUE THREAD

**Issue by rajeshgithub001** [Mimetis/Dotmim.Sync#246]
WebClientOrchestrator() doesn't working for multi scope environment.
At mobile side its not working. We are syncing using .net core web api. 
It syncing whole tables, multi scope doesn't work.

Find below setup code at mobile side :-

 var proxyClientProvider = new WebClientOrchestrator("http://xxxxxxxxxx/api/sync");
 var clientProvider = new SqliteSyncProvider("xxxxxxxx.db");

            // Create 2 tables list (one for each scope)
            string[] productScopeTables = new string[] { "T1" };
            string[] customersScopeTables = new string[] { "T2" };

            // Create 2 sync setup with named scope 
            var setupProducts = new SyncSetup(productScopeTables, "productScope");
            var setupCustomers = new SyncSetup(customersScopeTables, "customerScope");

            
            var agentProducts = new SyncAgent(clientProvider, proxyClientProvider, setupProducts);
            var agentCustomers = new SyncAgent(clientProvider, proxyClientProvider, setupCustomers);

            var progress = new SynchronousProgress<ProgressArgs>(s =>
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
                Console.ResetColor();
            });

            var remoteProgress = new SynchronousProgress<ProgressArgs>(s =>
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
                Console.ResetColor();
            });

            // Spying what's going on the server side
            agentProducts.AddRemoteProgress(progress);
            agentCustomers.AddRemoteProgress(remoteProgress);

          do
            {
                Console.Clear();
                Console.WriteLine("Sync Start");
                try
                {
                    Console.WriteLine("Hit 1 for sync T1. Hit 2 for sync T2");
                    var k = Console.ReadKey().Key;

                    if (k == ConsoleKey.D1)
                    {
                        Console.WriteLine("Sync T1:");
                        var s1 = await agentProducts.SynchronizeAsync(progress);
                        Console.WriteLine(s1);
                    }
                    else
                    {
                        Console.WriteLine("Sync T2:");
                        var s1 = await agentCustomers.SynchronizeAsync(remoteProgress);
                        Console.WriteLine(s1);
                    }

                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                }
            } while (Console.ReadKey().Key != ConsoleKey.Escape);

Is it not supporting ?

**Comment by Mimetis** [comment]
Hey @rajeshgithub001 

This issue was already raised (but I did not find which issue it is :) )
The HTTP mode for multi scope will be added in the next version `v0.5`

Hopefully before the end of April

**Comment by rajeshgithub001** [comment]
> Hey @rajeshgithub001
> 
> This issue was already raised (but I did not find which issue it is :) )
> The HTTP mode for multi scope will be added in the next version `v0.5`
> 
> Hopefully before the end of April

Any tentative date ? Actually if its coming then we will go forward with this framework ....!

**Comment by rajeshgithub001** [comment]
Any tentative date ? Actually if its coming then we will go forward with this framework ....!

**Comment by Mimetis** [comment]
I will push a first version of the PR before end of next week, I promise :)

**Comment by Mimetis** [comment]
@rajeshgithub001 The `v0.5` branch is available.

You can test if from nuget. 

https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.0-beta-0299

You can manually install it, through this command line:
``` bash
dotnet add package Dotmim.Sync.Core --version 0.5.0-beta-0299
```

Or through Visual Studio
Be sure to select **Pre-release** to see the packages, inside Visual Studio

![image](https://user-images.githubusercontent.com/4592555/78261943-2e922180-7500-11ea-970c-30a1bc69b528.png)

Or you can directly grab the code from the branch ``Mimetis-v0.5` here : https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5
You will have to clone it locally and rebuild it, to use it.
Rebuild:
- `Dotmim.Sync.Core`
- `Dotmim.Sync.MySql`
- `Dotmim.Sync.Sqlite`
- `Dotmim.Sync.SqlServer`
- `Dotmim.Sync.SqlServer.ChangeTracking`
- `Dotmim.Sync.Web.Client`
- `Dotmim.Sync.Web.Server`

**Be careful, there is some breaking changes, and the doc is not up to date with these changes.**

If you want to test it, be sure to start from a **fresh new server and client databases**, because there is no "upgrade path from `v0.4` to `v0.5`" ... *yet*

If you need some example, do not hesitate to search in:
- Tests projects: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Tests/Dotmim.Sync.Tests 
- Console sample: https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Dotmim.Sync.SampleConsole
- Web Api project: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Samples/Dotmim.Sync.SampleWebServer

If you are testing this version, let me know what you find / need
