### ISSUE TITLE
What will be the tentative date for supporting multiscope for web api ?

### ISSUE THREAD

**Issue by rajeshgithub001** [Mimetis/Dotmim.Sync#247]
Sorry i didn't know how to reopen issue again.
Let me know the tentative/actual date you think you will release supporting multiscope for web api ?

**Comment by Mimetis** [comment]
Official release : End of April
Pull Request availability on the Githu repo : Before April 10

**Comment by Mimetis** [comment]
@rajeshgithub001 The `v0.5` branch is available.

You can test if from nuget. 

https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.0-beta-0299

You can manually install it, through this command line:
``` bash
dotnet add package Dotmim.Sync.Core --version 0.5.0-beta-0299
```

Or through Visual Studio
Be sure to select **Pre-release** to see the packages, inside Visual Studio

![image](https://user-images.githubusercontent.com/4592555/78261943-2e922180-7500-11ea-970c-30a1bc69b528.png)

Or you can directly grab the code from the branch ``Mimetis-v0.5` here : https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5
You will have to clone it locally and rebuild it, to use it.
Rebuild:
- `Dotmim.Sync.Core`
- `Dotmim.Sync.MySql`
- `Dotmim.Sync.Sqlite`
- `Dotmim.Sync.SqlServer`
- `Dotmim.Sync.SqlServer.ChangeTracking`
- `Dotmim.Sync.Web.Client`
- `Dotmim.Sync.Web.Server`

**Be careful, there is some breaking changes, and the doc is not up to date with these changes.**

If you want to test it, be sure to start from a **fresh new server and client databases**, because there is no "upgrade path from `v0.4` to `v0.5`" ... *yet*

If you need some example, do not hesitate to search in:
- Tests projects: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Tests/Dotmim.Sync.Tests 
- Console sample: https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Dotmim.Sync.SampleConsole
- Web Api project: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Samples/Dotmim.Sync.SampleWebServer

If you are testing this version, let me know what you find / need

**Comment by rajeshgithub001** [comment]
I try to do partial sync of tables from mobile side.

var clientOptions = new SyncOptions
            {
                ScopeInfoTableName = "ProdToFindScope",
                BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "sync_client"),
                BatchSize = 50,
                CleanMetadatas = true,
                UseBulkOperations = true,
                UseVerboseErrors = false,
            };

            var clientSetup = new SyncSetup
            {
                StoredProceduresPrefix = "cli",
                StoredProceduresSuffix = "",
                TrackingTablesPrefix = "cli",
                TrackingTablesSuffix = "",
                TriggersPrefix = "",
                TriggersSuffix = "",
            };

I able to do only one table sync by using below code without SyncSetup & SyncOptions:-

            // Create 2 agents, one for each scope
            var agentProducts = new SyncAgent(clientProvider, proxyClientProvider, "ProdToFindScope");

What is the impact of following : - ?

var clientOptions = new SyncOptions
            {
                ScopeInfoTableName = "ProdToFindScope",
                BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "sync_client"),
                BatchSize = 50,
                CleanMetadatas = true,
                UseBulkOperations = true,
                UseVerboseErrors = false,
            };

            var clientSetup = new SyncSetup
            {
                StoredProceduresPrefix = "cli",
                StoredProceduresSuffix = "",
                TrackingTablesPrefix = "cli",
                TrackingTablesSuffix = "",
                TriggersPrefix = "",
                TriggersSuffix = "",
            };

**Comment by rajeshgithub001** [comment]
> @rajeshgithub001 The `v0.5` branch is available.
> 
> You can test if from nuget.
> 
> https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.0-beta-0299
> 
> You can manually install it, through this command line:
> 
> ```shell
> dotnet add package Dotmim.Sync.Core --version 0.5.0-beta-0299
> ```
> 
> Or through Visual Studio
> Be sure to select **Pre-release** to see the packages, inside Visual Studio
> 
> ![image](https://user-images.githubusercontent.com/4592555/78261943-2e922180-7500-11ea-970c-30a1bc69b528.png)
> 
> Or you can directly grab the code from the branch ``Mimetis-v0.5` here : https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5
> You will have to clone it locally and rebuild it, to use it.
> Rebuild:
> 
> * `Dotmim.Sync.Core`
> * `Dotmim.Sync.MySql`
> * `Dotmim.Sync.Sqlite`
> * `Dotmim.Sync.SqlServer`
> * `Dotmim.Sync.SqlServer.ChangeTracking`
> * `Dotmim.Sync.Web.Client`
> * `Dotmim.Sync.Web.Server`
> 
> **Be careful, there is some breaking changes, and the doc is not up to date with these changes.**
> 
> If you want to test it, be sure to start from a **fresh new server and client databases**, because there is no "upgrade path from `v0.4` to `v0.5`" ... _yet_
> 
> If you need some example, do not hesitate to search in:
> 
> * Tests projects: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Tests/Dotmim.Sync.Tests
> * Console sample: https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Dotmim.Sync.SampleConsole
> * Web Api project: https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-v0.5/Samples/Dotmim.Sync.SampleWebServer
> 
> If you are testing this version, let me know what you find / need

Looks great. Thanks.

**Comment by Mimetis** [comment]
> Can we have the detailed documentation of SyncOptions & SyncSetup !

Sorry, for now, you will have to look the code , the tests projects and the sample, to understand
Basically, 
- `SyncOptions` are the options used for the local database
- `SyncSetup` descibes the tables / colonnes / filters you want to be part of the sync.

> Another concern is that there is no upgrade path from .4 to .5 version as said above

Indeed. No path to upgrade from `v0.4` to `v0.5`

I did not test yet, but i think it should not be too complicated

- On the server side, you have to generate two databases : Create an empty project, generate the sql on a dummy server db, then replicate the database in your own database
- Same on the client. Maybe you will have to update the in place sync table, since there is more columns

Once again, `v0.5` is not yet released, and it's provided **as is**
Once all the tests will pass and I will be happy with this version, I will update the doc, and I will make a doc for upgrade.
