### ISSUE TITLE
What would be missing to have a full feature sync framework ?

### ISSUE THREAD

**Issue by Mimetis** [Mimetis/Dotmim.Sync#255]
Hey guyz.

I've finally reach a point, where I've almost done all the features I wanted to develop for this framework.

I still have some more things to add, like:
- An **advanced filter management**, where changing a value from a filter, should remove the lines from any client that is not any more part of the filter.
I tried several solutions to get a universal solution that will work in almost all cases, but it's really, really really hard .... So far, I've no idea if I will be able to implement such system...
- A **logging system**.  This is something that is missing, definitively, and it's not really complicated to integrate. I'm not yet decided on what kind of system I should go, and if you have any idea, I would love to hear from you

Other than that, I'm pretty happy with the actual features in place in the last version.

Do you think of anything that is missing, and would be an absolute required feature, for you ?

**Comment by champcbg** [comment]
I agree logging is very important.

**Comment by YoussefSell** [comment]
definitely logging is an important feature to be considered,

and I would add a discussion on the possibility of providing a Javascript web client-provider, what we should consider when building it!?, and is it even possible (it not gonna be hard), I looked into the actual web client and is depending on the core package, so we should abstract some of the core features into a JS implementation and build the JS client on top of it.

this feature will be interesting, and it will open the door for many possibilities

**Comment by Mimetis** [comment]
Hi @YoussefSell 
Thanks for feedback
Logging is partially implemented in the last version, but I did not had the time yet to make the documentation

Regarding the JS implementation, it's quite complicated depending the scenario

For web browser, old plain vanilla JavaScript, since we don't have a relational database out of the box, for web client, it's nearly impossible to adapt.
**Web Sql** has been deprecated in flavor of NoSQL database **IndexedDB**. See more here : https://hacks.mozilla.org/2010/06/beyond-html5-database-apis-and-the-road-to-indexeddb/
This type of local storage for browser is not compatible at all with `DMS`

If you talk about JS as a language used in an electron application, reactjs native and so on, so the response is Yes, it's possible, assuming we are migrating the whole client side of the `DMS` framework.
But it will be a really complicated task and the maintenance will be hard. 
I'm not sure it's worth it, to be honest.

Last but not least, we can talk about migrating the server side as well to JS, supported by NodeJS.
Once again it's a really complicated task, but still feasible. 
In that case, I think it's a complete new project to develop, based on the architecture and algorithms already in place within `DMS`.
I've think about that new project for a long time, but did not find the time to even starting something.
Once again I'm not sure it's worth it to create a NodeJS version, but I may be wrong.

**Comment by gentledepp** [comment]
Logging is indeed very important.
Especially the time it takes to execute the separate sync steps and the amount of rows transferred are interesting.
And also some detailed information on sync conflicts that appear so that it is easier to pinpoint the issue.

We are actually using dotmim.sync events to gather such information and send them as custom events to Microsoft Application Insights.

One addition we **had** to make was to add a handler that gets any exception from dotmim.sync on the serverside and allows us to log it.
Because (correct me if I am wrong, because we're using an old version of DMS) all exceptions are caught by dotmim.sync, wrapped into a response message and sent to the client with a 200 success code, montitoring systems like Application Insights and the like cannot automatically pick up any failed requests which is pretty bad.
So if you could find a solution for this (allow to throw an exception to the client without completely swallowing the exception itself) would be awesome

**Comment by gentledepp** [comment]
Regarding the **advanced filter management**
there is a solution for Microsoft Dynamics called "Resco".
They solved this problem the following way:
1) Sync filters are only filtering on the server side on the **initial** sync
2) Incremental changes are distributed to **all clients** without filtering on the server side
3) rather, the clients know the sync filters themselves and thus just delete invalid rows on the client side

This is a very flexible solution, where you can even change sync filters afterwards.
The obvious drawback is that incremental changes are always distributed to all clients. This can be a lot of data and hence we opted for a different solution.

**Comment by Mimetis** [comment]
Logs is already in place, I just need to make the doc :)

For the filter purpose, thanks for the solution. Do you have any pointer on any doc ?

**Comment by gentledepp** [comment]
Sure!
Resco.Net has a sample application called "Woodford" and it contains a section for [Sync Filters](https://docs.resco.net/wiki/Sync_Filter)
At the bottom of the page, there is a forward link to [some additional documentation on this](https://infinite-usa.com/sync-filter/)

**Comment by gentledepp** [comment]
I just read through the docs and here is my wishlist ;-)



1. Reinitialize when outdated? https://dotmimsync.readthedocs.io/Synchronize.html#forcing-reinitialize
	If we have to do this ourselves, can you add this as a sample to the docs?
	Ah! I just found it [here](https://dotmimsync.readthedocs.io/Metadatas.html) so maybe just add a hint to "forcing-reinitialize" ;-)
	
2. Reinitialize when using [MSSQL Change Tracking](https://dotmimsync.readthedocs.io/ChangeTracking.html) 
	If setup with a retention of 14 days, what happens if a client connects after 15 days? Will it be reinitialized correctly?
	
	
3. Nice-to-have: Sub-progress for each batch that is uploaded/downloaded so that huge, long running uploads/downloads still show progress (eye candy) 
	https://dotmimsync.readthedocs.io/Progression.html

4. ‼ A warning on using the local SQLiteProvider due to transaction-overlappings (no timestamp exists on sqlite)

5. Command caching - as I already showed in an older issue, Command caching signifficantly improves performance when you are transferring a lot of rows (not dozens, but thousands)
	Is this already implemented? (Because the issue was removed)

6. AspNet (WebApi 2) is crucial to us - we'll have to implement it ourselves then.

7. ‼ When using the [DMS Web API](https://dotmimsync.readthedocs.io/Web.html) in a scaleout scenario (multiple web servers), memorycache will not be the right choice for session management.
	Does DMS have support for Redis as well?
	
8. The `Get()` endpoint shows the server side config and ["shows only if Environment == Development"](https://dotmimsync.readthedocs.io/Web.html)
	Can we override this? Maybe we want to allow administrators to still be able to look at this in production
	
9. 🎉 [SerializerConverter](https://dotmimsync.readthedocs.io/SerializerConverter.html) This is awesome! 
	Regarding MessagePack - this will very likely not work, because ContractlessStandardResolver may user dynamic/IL code generation. On UWP (because of .net Native) and on iOS (where IL emit is also forbidden) this causes a huge headache.
	So basically, we'd have to subclass all the serialized classes, annotate them with MessagePack attributes ([Key(0)] on each property -  see [MessagePack CSharp Quickstart](https://github.com/neuecc/MessagePack-CSharp#quick-start)) and serialize those :-|

10. [Snapshots](https://dotmimsync.readthedocs.io/Snapshot.html) are a great idea. For a scaleout scenario, it would be great if you could also store these in blob storage!

11. In general, blob storage support would be a great addition to support scaleout scenarios!
	
12. Idea: Regarding adding and removing a table in chapter [provisioning](https://dotmimsync.readthedocs.io/Provision.html)
	One could actually track the timestamps per table so if you add a new table, it is re-synchronized automatically (because the default timestamp is 0) and all other tables just yield the changes since the last sync

	Also, why is adding a column so hard? (Removing should not be supported I guess, but adding a nullable column to a table should be absolutely doable - that would be a GREAT addition)

**Comment by lordofffarm** [comment]
One feature that could be useful in conflict resolution is per column update tracking, where update_timestamp is written down for each column, not just for the row.
Right now: 
Client 1 changes Column 1 of a record in a table at 00:00.
Client 2 changes Column 2 of the same record in the same table at 00:05.
Client 2 synchronizes at 00:10. Now value in Column 2 is of Client 2.
Client 1 synchronizes at 00:15. Depending on the conflict resolution policy:
if ServerWins, Client 1's Column 1 value is dismissed;
if ClientWins, Client 2's Column 2 value is overwritten by Client 1's stale (old) Column 2 value;

Is this the current logic? I haven't tried out the latest version yet.
With this feature, both new values of the columns should persist.

**Comment by lordofffarm** [comment]
Another useful feature is an ability to specify columns that need to be removed from the sync setup.
Specifying these columns in, for example, SetupTable could be really convenient instead of doing this through interceptors.

**Comment by Mimetis** [comment]
> Another useful feature is an ability to specify columns that need to be removed from the sync setup.
> Specifying these columns in, for example, SetupTable could be really convenient instead of doing this through interceptors.

This how it's working actually. 
See https://dotmimsync.readthedocs.io/Provision.html#migration

**Comment by gentledepp** [comment]
## 4 Warning using SqliteProvider due to transaction-overlappings (no timestamp exists on sqlite)
Sorry, I completely forgot to elaborate. This was a simple "note to myself"

So... on MSSQL, we do have the `min_activerowversion` that gives you the *lowest* timestamp that is currently being used in a transaction. So by using `min_activerowversion - 1` you get **the lowest timestamp not currently hidden by a transaction** and when storing it as `sync_timestamp`, you can be sure, that next time, when you only send incremental changes `> sync_timestamp` you will not miss any changes.

Now, on SQLite you do not have such a thing. Therefore you build the timestamps yourself.
Now what could happen is:
* row "customer A" has timestamp `t1`
* row "customer B" has timestamp `t2` but is hidden because it is still used in tx1 which is **not** yet committed
* row "customer C" has timestamp `t3` 

Now you sync at `t4` and send all changes (except "customer B" which is still hidden by tx1) to the server. 
Thereafter, you store `t4` happily and think that everything went fine.
However, "customer B" will **never** be sent to the server.

We fixed this issue by introducing some kind of `ReaderWriterLock` where 
* all database access by Dotmim.Sync uses a *write lock*
* all our domain logic code accesses the database using a *read lock* that is held for a full transaction
that way, during a sync, there cannot be any pending "domain logic transaction" (write lock can only be granted if there are NO open read locks)

So while I do not think that this should be a part of Dotmim.Sync, you'd better warn your users in your docs! ;-)

## 5 Command Caching
Have a look at this closed issue here:

![image](https://user-images.githubusercontent.com/1175751/84481329-39062f80-ac96-11ea-9471-c62fdd3c5f97.png)

Implementing command caching is not a lot of effort as your architecture makes it quite easy.
I did some measurements and added them to an issue, but I can't seem to find it.
So you have to believe me.
*Jedi-mode: on*: *You are convinced, that adding command caching is an absolute necessity!*

## 6 WebApi 2
well... we have a system installed at several customers that runs good old .NET.
We cannot just migrate that easily 😭

## 8 Get() endpoint
Awesome! 😎🤜

## 9 SerializerConverter
I'll think about it!

##12 Adding / Removing table
Well, **full** schema management would be an unnecessary overkill.
Nevertheless, it would be very NICE to be able to 
1. **add** a new table to a scope
2. **add** a new **nullable** column to a scope

Removing a table/column does not need to be supported, because that would break backward compatibility.
Remember, there may be clients supporting v1 of the schema and others, that already run on v2!
It is **very, very** uncommon, that you can upgrade *all* of your clients in one swoop!

With this functionality, clients just need to make sure to specify all columns explicitly in any Insert/Update query. (So no `SELECT * FROM sometablename`) Because if the server changes the schema, and the client still runs v1, it may unexpectedly get a new column and crash.

One thing left is, that if a client gets the new column, it *must* run a re-initialization on the sync. Otherwise, there may be some rows that already have a value in `New_Column`, but the client still has `null` values in it!

With the new table, this is much simpler, as clients that do not know them, will simply ignore them after all.

So I guess these features can be added afterwards as well.
I guess what would be needed is
* the server, when applying the sync setup, comparing the existing setup (stored in database?) with the one provided by code. If there is a change in one of the tables, it can store the `timestamp` of that change. So it *knows* **when** the sync config was changed.
When a client then synchronizes, the server can know, whether it is already aware of that table. If not, it can cause a `Reinitialization` of **this single table**! That'd be absolutely awesome!
