### ISSUE TITLE
MariaDB SyncProvider

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#301]
Hello,
are there any plans to enhance mysqlsyncprovider to support MariaDB or to add a MariaDB SyncProvider?
I think there shouldn't be many changes necessary for this.
Thanks
Reinhold

**Comment by Mimetis** [comment]
I'm not an expert regarding MySql & MariaDB
But Pull requests are opened :)
Feel free to contribute !!

**Comment by samcov** [comment]
Lack of a MariaDB provider, is a bit of a show stopper, as we're moving away from SqlServer for newer projects.

It's also a bit surprising since at the base level, they're pretty much the same, we migrated from MySql to Maria without changing a line of Sql.

**Comment by Mimetis** [comment]
The `MySqlSyncProvider` is using `MySqlConnector` to access `MySql`.
It seems that `MySqlConnector` is working also with `MariaDB` (ref: https://mysqlconnector.net/)

So, you should try the `MySqlSyncProvider`  "*as is*" and see if it's working or not.

**Comment by Mimetis** [comment]
I'm currently testing the `MySqlSyncProvider` and with a little modification in the base code, it's working pretty well with **mariaDB**

I will make PR to supports MariaDB today, that you will be able to test, if you're interested in.

**Comment by samcov** [comment]
Great!

**Comment by jader1313** [comment]
We also need this and we’re available to help test.

**Comment by Mimetis** [comment]
`MariaDB` branch merged into `master` :)
The `MySqlSyncProvider` is fully compatible with `MariaDB` now

I will probably create a new provider called `MariaDbSyncProvider`, but it will be just a rename of the `MySqlSyncProvider` since I'm using the same code base.

Honestly, I'm really surprised and impressed by the mariadb performance.
You can see it here : 
- [MariaDB Integration tests](https://dev.azure.com/dotmim/Dotmim.Sync/_build/results?buildId=458&view=logs&j=a332b0cc-6213-5aba-ae4b-284aafd5c3e6&t=d577d306-5420-5af8-e4af-2f91d10bf383): 3min7s
- [MySql Integration tests](https://dev.azure.com/dotmim/Dotmim.Sync/_build/results?buildId=458&view=logs&j=f28b2766-c77f-5700-fbec-7a15fb52f368&t=885d2a0d-2ec0-5a54-b95b-662ea45a4f39): 6min31s

You can give it a try, using the master branch code, and make me some feedbacks !

**Comment by Mimetis** [comment]
Just published a beta version here : https://www.nuget.org/packages/Dotmim.Sync.MariaDB/0.5.8-beta-0460

**Comment by Hardshop18** [comment]
I did some tests with MariaDB and the following error is occurring:

**Sync Start
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
        INSERT  INTO `usuario`
...' at line 46**

I don't know if it's some configuration I have to do in MariaDB, but to solve the problem I changed this line:

`SELECT ROW_COUNT() LIMIT 1 INTO sync_row_count;`

by:

`SELECT ROW_COUNT() INTO sync_row_count;`

**Comment by Mimetis** [comment]
what version of MariaDB are you using ?

**Comment by Hardshop18** [comment]
MariaDB Version 10.2.33

**Comment by Mimetis** [comment]
I have the version 10.5.5
Just curious, are you able to make the same test (with the `LIMIT 1`) with the last MariaDB version ?
Just curious if this is a new feature or if I missed something in my unit tests...

**Comment by Hardshop18** [comment]
I haven't tested it on the latest version of MariaDB. Because we are using this version 10.2.33 on AWS.

**Comment by Hardshop18** [comment]
I believe that because of the version I'm using, it may be that version 10.3.3 has corrected the problem (https://mariadb.com/kb/en/limit/). I did a test with console project in the latest version of MariaDB and it worked. I did another test with Dotmim with MariaDB and Xamarin.Forms, I identified that the async methods of mysqlconnector and Xamarin.Forms don't work.

**Comment by Mimetis** [comment]
Thanks for that feedback !

By the way, you should use web api to expose your maria db to your xamarin app, and use a local sqlite database locally

thanks for all !
