### ISSUE TITLE
SQL Server varbinary to BLOB Sqlite

### ISSUE THREAD

**Issue by vunder** [Mimetis/Dotmim.Sync#329]
SQL Server `varbinary` type in synching wrong into `BLOB` Sqlite
When data are sending from Sqlite to SQL Server data passes correct: C# `byte[]` (BLOB) converts to `varbinary(max)`. But on reverce direction SQL Server -> Sqlite, BLOB column gets string data `/9j/4AAQSkZJRgABAQEAtgC2AAD/2wBDAAMCAg...` and SqlReader fails with reading `byte[]` column

**Comment by vunder** [comment]
@Mimetis I'll check the differences. In tests data passes correct (as byte[]). But on my project, I'm receiving from the server changed row with string value.

**Comment by vunder** [comment]
@Mimetis after playing a while with tests I've found that when `Options.BatchSize=0` binary goes to Sqlite as string
With non-sero size it saves correct

**Comment by vunder** [comment]
I think the reason is that `SyncSet.ImportContainerSet` method without `BatchSize` is calling with `checkType=false`. In this way values are just copying without any transformation. After deserialization binary property is still has Base64 string value. In case there are no type check (BatchSize=0) value would be Base64 string. Changing parameter to `true` (WebClientOrchestrator.cs:393) would fix this

**Comment by Mimetis** [comment]
Thanks @Vunder for debugging this.
You're absolutely right.

The only *trick* is here, is that the `SyncRow` is just here to transition its array to the provider.
Then the provider should make the correct conversion.

Since we know that the provider WILL do a conversion, we should avoid to make a previous one before.

BUT it seems the provider did not do the good conversion anyway.

If you look carefully when the provider makes the conversion, when setting the parameter in `DbTableManagerFactory`, you will see that I forgot the `DbType.Binary` conversion :( 

https://github.com/Mimetis/Dotmim.Sync/blob/15c1e66dc77281d5e9ff2500c345c67b01e4ae4d/Projects/Dotmim.Sync.Core/Manager/DbTableManagerFactory.cs#L68-L111

I made a PR to fix that and make a kind of uniformization of conversion type, using the `SyncConvertType` class:

``` csharp
            if (value == null || value == DBNull.Value)
                parameter.Value = DBNull.Value;
            else
                parameter.Value = SyncTypeConverter.TryConvertFromDbType(value, parameter.DbType);
```

It should have resolved the issue.
I'm currently testing the fix and if all the tests are good, I will push a new version 

thanks @vunder for your help !

**Comment by Mimetis** [comment]
It should be resolved now, with the last commit on the master branch (version `0.5.8`)

**Comment by vunder** [comment]
@Mimetis I'll check this today and let you know

**Comment by vunder** [comment]
@Mimetis Confirm, latest changes behaves correct
