### ISSUE TITLE
Question - Is it possible to have different client side schema to server when rolling out update? 

### ISSUE THREAD

**Issue by keithmullins** [Mimetis/Dotmim.Sync#339]
I hope it's okay to post a question here!

I am working on a .NET client application that needs to sync data from a cloud server through a WEB API. We are currently doing this by using a modified date column in the SQL Server database but this is proving problematic! Your framework may just be the answer :-) I have been looking for a long time for something like this framework - it really is excellent but there is one thing I can't quite figure out from reading the docs and making some test applications.

Let's say my clients are all on version 0.1 and have a particular schema. All clients talk to my WEB API v0.1 and everything works great. I then have a new version of my WEB API, v0.2, with new tables and columns that I need to add to my sync. However, I don't want my clients running v0.1 to get these new tables and columns. I only want those new columns and tables to be synced with clients running a new v0.2 of the software, and I want to roll out my new v0.2 version slowly to all clients. So there will be a period of time where my v0.1 clients will be connecting to my v0.2 WEB API. Is this possible? Any time I've tried changing my server side like this it seems to breaks the client side. The only way that I can think to get it to work is to create a new application in IIS for each WEB API release so that they are completely separate URLs. 

Apologies if I have missed something in the docs that explains this but all of the examples suggest that the server and client need to always have the same schema.

**Comment by vunder** [comment]
@keithmullins I have a sort of the same problem. I guess it is possible to do via "scopes". But have not tested such solution yet. The idea is to have scope the same as client's database version.

**Comment by Mimetis** [comment]
Hey @keithmullins 

As @vunder says, using different *scopes* **should** work (not tested yet) (let say scope `v1` for first version and `v2` for new version with new tables / columns)

Well, today I guess it **may** not work because you may have conflicts with the generated stored procedures at some point.

This is one of the question I'm currently working on (#321) 
If we decide to remove all the generated stored procedures and rely only on *in memory* statements, it will become easy to distinguish different `Select` / `Update` or `Delete` statements depending on the scope name, the tables involved and the columns to sync.

Even though, If you're relying on scopes versioning (and I think it will be the solution, in the next release ;) )
You may be aware that it will work only if :
- You're working with the same primary keys in the table, because the tracking table IS using the primary keys as its own primary keys
- If you're adding columns, be sure these columns allows null otherwise scope `v1` will not work anymore
- If you're removing columns ... well It will be complicated I guess for the scope `v1` to continue to work correctly
- You should declare all the columns in the `SyncSetup` object (not only the table name) otherwise the `v1` scope will be `All` columns (only problematic for new client who come in the game and wants the `v1` scope)
- Oh god, and a lot of others things to think about :)

Anyway the first step before think about versioning scopes, is to take a decision about removing the stored procedures.
And today the stored procedures have better performances than the  *in memory* commands.

It's definitively something I'm looking for today.

Until then, you can play with [Provision, Deprovision and Migration](https://dotmimsync.readthedocs.io/Provision.html) to have a new version, but it could be a little bit tricky, and you will not have the `v1` anymore at the end, I guess.

We already had this discussion with @gentledepp. I guess he has some good feedbacks too on this particular question.

If you have any ideas / thoughts, do not hesitate to share !

**Comment by keithmullins** [comment]
Thanks @Mimetis and @vunder for your quick replies!

So I ran a quick test using scopes and it seems to let me have separate local schemas (which is great!!) but I still get an error when trying to sync my new column!

For my test I am doing the following in the `Startup.cs` of the WEB API project:
```
var tables = new string[] { "Prices" };

/*  Create my v1 scope  */
var v1SyncSetup = new SyncSetup(tables);
v1SyncSetup.Tables["Prices"].SyncDirection = SyncDirection.DownloadOnly;
v1SyncSetup.Tables["Prices"].Columns.AddRange(new string[] { "Id", "StoreId", "ProductId", "Value" });
v1SyncSetup.Filters.Add("Prices", "StoreId");
services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, "v1", v1SyncSetup);

/*  Create my v2 scope  */
var v2SyncSetup = new SyncSetup(tables);
v2SyncSetup.Tables["Prices"].SyncDirection = SyncDirection.DownloadOnly;
v2SyncSetup.Tables["Prices"].Columns.AddRange(new string[] { "Id", "StoreId", "ProductId", "Value", "NewCol" });
v2SyncSetup.Filters.Add("PosRetailPrices", "StoreId");
services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, "v2", v2SyncSetup);
```
I have added a new `NewCol` column to the table for testing purposes. It is `NULLABLE`.

On my client app I pass in the `scopeName` when creating my `SyncAgent`

Test App `v1`:
`var agent = new SyncAgent(clientProvider, serverProvider, "v1");`

Test App `v2`:
`var agent = new SyncAgent(clientProvider, serverProvider, "v2");`

This results in both applications running side-by-side connecting to the same WEB API but having different schemas locally! So far so good! The clients are both running OK but the data in `NewCol` is not syncing to my `v2` app.

In order for the data in `NewCol` to actually sync down I manually updated the store procedures to include the new column in the `SELECT` - is this correct? This resulted in `v2` getting the correct data but `v1` throwing an exception:
`Unhandled exception. Dotmim.Sync.SyncException: Column is null`

I know there are ways to change the schema through code using Provision and Deprovision but will this result in the same exception being thrown? I understand there may be some magic going on that I would have bypassed by updating the procs manually :)

When you said
> Well, today I guess it may not work because you may have conflicts with the generated stored procedures at some point.

maybe this is what you were referring to?

I would think that moving away from store procedures and using *in-memory statements* as you suggest would get around this problem! I'm happy to try and help you with this - it would be of great benefit to me to have this working.

**Comment by keithmullins** [comment]
I had a *eureka* moment this morning - "maybe I could suffix the stored procedures with the version too". It's probably obvious to more experienced people but I'm new to the framework :-)

So I just changed my sync setup:
```
var v1SyncSetup = new SyncSetup(tablesv1)
{
    StoredProceduresSuffix = "_v1"
};

var v2SyncSetup = new SyncSetup(tablesv2)
{
    StoredProceduresSuffix = "_v2"
};
```

I now have `v1` and `v2` client apps running with different local schemas and syncing with my WEB API without errors.

I still need to do a lot of testing but this seems to be working as I want.

**Comment by Mimetis** [comment]
Indeed.
In a future version, all the stored procedures will have the scope name part of their naming convention, so you will not have to change the prefix anymore to have multiples versions of the stored procedures
