### ISSUE TITLE
Do you support scenarios confirmed by users

### ISSUE THREAD

**Issue by bxjg1987** [Mimetis/Dotmim.Sync#340]
Sometimes users need to see the data to be synchronized, and then confirm whether to synchronize. Is this scenario supported?

**Comment by Mimetis** [comment]
Yes, 
you can call `GetEstimatedChangesCountAsync()` on the `SyncAgent.LocalOrchestrator` if you want an estimation of the rows to download from the server

You can call as well `GetChangesAsync` that will get the changes from the server (but will not apply them)

Please note that the results you will have will be **estimation** because a lot of things can happen when you launch the real synchronization: Conflicts, new rows, deleted rows and so on ...

**Comment by bxjg1987** [comment]
@Mimetis thank you! Like this project very much, will continue to pay attention to!
