### ISSUE TITLE
SqlSyncProvider doesn't support datetime2

### ISSUE THREAD

**Issue by BluePalmTree** [Mimetis/Dotmim.Sync#364]
Hello,

i'm trying to setup a simple example to test dotmim.sync via HTTP. But I get the following error:

```
Message=The Column Timestamp of type datetime2 from provider SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider is not currently supported.
Source=Dotmim.Sync.Web.Client
```

Is there a workaround besides change the datatype in the database?

**Comment by Mimetis** [comment]
I think your problem is coming from the naming of your column `Timestamp`
Since it's a reserved key word, it's not allowed here.

You can see the check method here:

https://github.com/Mimetis/Dotmim.Sync/blob/6ef08f8d3ce517854a30614ab5627d3d158ac2bc/Projects/Dotmim.Sync.Core/CoreProvider.Schema.cs#L138-L152

So far, if you can't rename this column, I guess you can clone the repository and remove this condition, recompile and test

**Comment by BluePalmTree** [comment]
The name was the issue.
Thank you very much.
