### ISSUE TITLE
Sync Like Merge Replication

### ISSUE THREAD

**Issue by PardeepBhandari** [Mimetis/Dotmim.Sync#408]
Hi

In merge replication there are two types of subscription server and client
in server subscription subscriber can further act like server (publisher).

my need is i want to provide each my client a switch which export its data to a server and further a mobile app fetch this data

I am able to sync data from my client to my pc and app can import data from my pc to mobile app
my pc has a static IP.

but issue is 
In first step syncing my pc act like a client and client pc act like a server.      
In second step my pc act like a server and mobile app act like client.

How can i achieve this. Help

**Comment by Mimetis** [comment]
You can't with `DMS`.
`DMS` is built to be a `Server` - `Client` framework. 
By default, a `Client` can't act as a `Server`.
To go a little bit more in depth, once a `Server` start to sync all the tracking records id have a `GUID` identifier. 
For a server this guid is allways `Guid.Empty` (`00000-000-000-00000`)
And each client has a new Guid generated, that is not a Guid.Empty, obviously.
That's why a `Client` can't act as a `Server`.

Maybe you can play with the `Interceptors` to do something similar (all the `OnSomething()` methods), but not sure at all.

**Comment by PardeepBhandari** [comment]
Hi

What if I restore my client's Database on my pc first and then built a client server relationship my pc act like server and client pc act like client and mobile app act like client. is it OK.

**Comment by Mimetis** [comment]
I don't know, you have to test the scenario I guess !
