### ISSUE TITLE
Use snapshots with historical data

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#419]
I've been unable to work out how to use snapshots with historical data. Each of our customers has a database with an ~identical schema. Some of our customers have been with us for over 20 years. We are investigating DMS as we move our customers to SQL Server (via web api) and SQLite on the client

If we were to create snapshots of our customer databases, they would reflect the current state. Is that correct? How do we create snapshots for historical data so that we can sync server data to client machines?

An alternative I've considered is to recurse the object hierarchy to sync the tables one at the time. I did this to sync initial client data to the server. Now the challenge is to get that server data to other clients in the same company.

We already pass the database name to the sync controller, so I tried also passing an optional table name. I reconfigured the sync agent on the client to take an optional tableName parameter, like this
```
string serviceUri = $"{SyncApi}?databaseName={DatabaseName}&tableName={tableName}";
if (string.IsNullOrWhiteSpace(tableName))
    serviceUri = $"{SyncApi}?databaseName={DatabaseName}";

WebClientOrchestrator webClientOrchestrator = new WebClientOrchestrator(serviceUri);

SyncAgent syncAgent = new SyncAgent(clientProvider, webClientOrchestrator, syncOptions);
if (!string.IsNullOrWhiteSpace(tableName))
{
    string[] tables = new string[] { tableName };
    syncAgent = new SyncAgent(clientProvider, webClientOrchestrator, syncOptions, tables);
}
```

I have modified the sync controller similarly
```
string[] tables = new string[] { tableName };
orchestrator.Setup = new SyncSetup(tables);
```

This syncs the correct tables without error on the client nor the server, but no data is returned. I also note no tracking tables are created on the client.

Startup on the web api is configured like this
```
SyncOptions syncOptions = new SyncOptions();
syncOptions.BatchSize = 2000;
syncOptions.UseBulkOperations = true;
services.AddSyncServer<SqlSyncChangeTrackingProvider>(myConnectionString, new SyncSetup(), syncOptions);
```
If we can't use snapshots with historical data, how to we configure DMS to sync one table at a time?

Or am I being a complete goose?

**Comment by Mimetis** [comment]
Not sure I'm understanding your question.
Just for info, Snapshots are only useful for **Client Initialization**
It's the only time where they are used.
Once the client database has been initialized, the snapshot is not used anymore.

Do you need to sync your historical data from the Server to one client that has already done several sync ?
If this is the case, Snapshot won't help here.
Once again, use snapshot to speed up new client databases initialization.

Make sense ?

**Comment by VagueGit** [comment]
My apologies for not being clear. One of our apps uses Realm Cloud. Realm syncs data from a cache on the client. We are experimenting with migrating this app to DMS.

Step 1: Migrate the client Realm cache to a new SQLite database.
Step 2: Use DMS to sync the SQLite data to a new SQL Server database through web api.
Step 3: Use DMS to sync the SQL Server data down to new SQLite databases on other clients in the same company.

We are stuck on Step 3. My understanding is that a snapshot is created at a point in time. If we create a snapshot after we do the initial upload to SQL Server, that snapshot will contain all the data, not just a most recent subset. Have I misunderstood?

**Comment by Mimetis** [comment]
The snapshot contains always all the data from 0 to T (T is time you create the snapshot)
Be careful , if you have filters, you need to create a snapshot per filter value

**Comment by VagueGit** [comment]
That's what I thought. So if we create a snapshot after initialising the server with 20 years of data, the snapshot will contain 20 years of data. Is that correct?

How then do we get all that data to the other clients?

**Comment by Mimetis** [comment]
It will contains all the rows from the server, filtered if needed.

Each new client that respect the filter, will get the snapshot IF it's a new client database
You should make some tests I guess

**Comment by VagueGit** [comment]
But we need to get 500mb onto each client from the server. How will a 500mb snapshot help?

**Comment by Mimetis** [comment]
It prevents the server to generate it on the fly on the first request from a client

Imagine that generating the first batch files for a new Client makes, let's say ... 12 min.

What happens on first sync from a client is:
- Client launches a sync
- Server sees it's a new client
- Server gets all the rows from the database (filtered if needed) and generates the batch files ------> 12 min work
- Clients download all the files from the server
- Clients applies all the rows locally

As you can see, you may have a `Timeout` on step 3, because client won't have answer before 12 min, right ?

Now imagine another scenario:

You are generating a snapshot, let's say, every 10 days, during the night.

What happens now on a first client sync:
- Client launches a sync
- Server sees it's a new client
- Server has already a snapshot generated (let's say 2 days ago)
- Server serves the snapshot files to the client (instantatly because the files have been generated 2 days ago, right ?)
- Client downloads all the files from the snapshot
- Client applies the snapshot locally
- Clients asks all the changes occured from 2 days ago to NOW
- Server gets all the rows from 2 days to NOW, and generate the batch files in less than 30 sec
- Client download the batch files from the server
- Client applies the delta rows locally

You're done without any pressure on the server and without timeout

Make sense ?

**Comment by VagueGit** [comment]
Yes I understand why it is good practice to generate a snapshot every two weeks after the server data has been uploaded. The problem we have is that we have to get all the data down to other clients in the same company on the same day it is initially uploaded.

How do we do that?

**Comment by Mimetis** [comment]
I can't say more, sorry, I don't see what you mean.
Maybe you should try to create a simple repro of your prob, otherwise, I don't know how to help you more

**Comment by VagueGit** [comment]
Sorry but I can't create a simple 500mb repo, but that's what we have to download to clients without disrupting their work.

If we create a snapshot today of 500mb of data, will that 500mb snapshot download as you describe?

**Comment by VagueGit** [comment]
My apologies. I've misunderstood what snapshots are. In SQL Server a snapshot is a copy of the database. I thought DMS snapshots invoked a process to take a snapshot of the SQL Server database, where in fact the DMS snapshot writes the database into json files.

Thank you @Mimetis for your patience.
