### ISSUE TITLE
Error with MySqlConnector

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#438]
DMS version: 0.6.1
Server: MariaDB
Local: SQLite
Table count: 10
Total rows: 1000000

I use MySqlConnector (https://mysqlconnector.net/) to connect to MariaDB and I get an error when launching agent.SynchronizeAsync() : "Could not load type 'MySql.Data.MySqlClient.MySqlConnection' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxx'."

**Comment by Mimetis** [comment]
Which version of **MySqlConnector** are you using ?
Be Careful, due to some incompatibilities  you need to downgrade to version `0.69.10`

Give a try with this downgraded version and let me know if it's working

**Comment by sylverbee** [comment]
I use 1.2.1
I tried to downgrad => all MySqlConnection are not anymore defined!
Haven't you got another solution?

**Comment by Mimetis** [comment]
You have to change `using MySql.Data.MySqlClient` with `using MySqlConnector`

Otherwise, you can clone the `Dotmim.Sync` repository, change the reference in the source code to use the last version of `MySqlConnector` and recompile.

In a future release, when compatibility will be resolved I will upgrade to the last MySqlConnector version.

**Comment by sylverbee** [comment]
Removing nuget MySqlConnector solves the problem.
Thx

NB : thx for the work done, it's a great extension!
