### ISSUE TITLE
Monitoring sync progress

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#464]
Does sync progress refer to the current batch, or total to be synced?

When migrating our customers to DMS we might have to initially sync 500mb for a customer using batch size 2000, a lot of batches.

I've read [Progression](https://dotmimsync.readthedocs.io/Progression.html#progression) but being a complete goose,  it is not clear to me how we would return to a variable either:

- the percentage synced (`decimal percent =` ...)
- whether or not sync was ongoing or completed `(bool isSyncing =` ...)

We sync SQLite through http to SQL Server. We are only interested in the local client. One or 2 lines of code that I could drop into our sync configuration without having to think too much would be greatly appreciated :-) 

**EDIT:** Some might argue this question is a How To rather than an issue. However our customers don't generally expect details of sync progress as shown in the docs. They just want to know if it is done, or how long to go. It isn't clear from the docs how this is achieved. So in that regard it might be considered an issue with the docs.

Of course I'm willing to accept the question is answered in the docs and I've missed it.

**Comment by Mimetis** [comment]
### 1 Percentage
Since the version `v0.6.1` you have the progression percentage in the `IProgress<ProgressArgs>` 
Check the discussion here : https://github.com/Mimetis/Dotmim.Sync/discussions/415#discussioncomment-327819
You have a new property called `ProgressArgs.PogressPercentage` that is a double value, representing the progression percentage.

### Sync Ongoing or not
You have multiple way to know if a sync is in progress.
you can wait until sync is done (when you get the result of `await agent.SynchronizeAsync()`

You have an event raised as well 
``` cs
agent.SessionStateChanged += (sender, state) => Console.Writeline(state)
// state could be Ready on Synchronizing
```

You can intercept the `agent.LocalOrchestrator.OnSessionEnd(ose => {})` as well.
