### ISSUE TITLE
Errors in documentation @ Filters chapter

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#466]
Please review and update [https://dotmimsync.readthedocs.io/Filters.html#example](url)
=> many filters are wrong in example and lead to misunderstanding

**Comment by Mimetis** [comment]
Thanks @sylverbee, I will check the doc. Or you can submit a PR with the correction as well :)

**Comment by sylverbee** [comment]
Another update you could do : change parameter name `City` to something else. It's confusing with column name (eg `CityParam`)

_Btw your package is a killer one!_

**Comment by sylverbee** [comment]
Something is wrong on **orderDetailsFilter**
`orderDetailsFilter.AddJoin(Join.Left, "SalesOrderHeader").[On]("SalesOrderHeader", "SalesOrderID", "SalesOrderHeader", "SalesOrderID")` => link to itself...

@Mimetis Could you correct and tell me? I'm blocked on my side (see discussion [https://github.com/Mimetis/Dotmim.Sync/discussions/467](url))

**Comment by Mimetis** [comment]
Thanks @sylverbee, I'm gonna check the filter sample to be sure it's working correctly

**Comment by Mimetis** [comment]
Thanks @sylverbee  for the bug in the filter on `SalesOrderDetail` and `SalesOrderHeader` !

Regarding your remark on `City`, it's intended.

When you are creating a `SyncParameter`, you have to define its name, type and default value. It's called **custom parameter**.

You can also create a `SyncParameter` that maps *exactly* to a column.It's called a **mapped parameter**: 
Instead of declaring the name, type, value, you can just point to an existing column and `DMS` will extract everything needed from this column.

This is exactly what happens with `City`.

Let's see in details this `AddParameter` call:
``` cs
var customerFilter = new SetupFilter("Customer");
customerFilter.AddParameter("City", "Address", true);
```
Internally, `DMS` will get the `City` column from the `Address` table, and then will create the parameter with the correct type, length and default value.
It's equals to:
``` cs
customerFilter.AddParameter("City", DbType.String,  true, null, 50) 
// parameter named City with type of string, null allowed, no default value, max length 50;
```

So far, choose between:
- Let `DMS` infers everything from the table
- Create your own parameter, but specify everything

Make Sense ?

**Comment by sylverbee** [comment]
Sounds perfect. Many thxs!
