### ISSUE TITLE
Enhancement - use httpresponse to stream baches into a file directly and not keep it in memory

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#471]
[This MSDN article](https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh781239(v=win.10)?redirectedfrom=MSDN#create-the-httpclient-send-the-get-request-and-retrieve-the-response) mentions that you should stream responses if the content is larger than 50 MB. 

However, I am sure that on mobile platforms (especially Xamarin.Android), this limit is hit much sooner.
So maybe, @Mimetis , the framework should only read the headers and stream the response into a local file (at least when downloading batches?)

[Here is a quite nice article going over this topic](https://www.tugberkugurlu.com/archive/efficiently-streaming-large-http-responses-with-httpclient)

What do you think?

**Comment by Mimetis** [comment]
Hey @gentledepp 
This improvement should benefits any platform for sure, especially mobile app.

I was really excited when I read the article you mentioned.
Unfortunately, unless I refactor A LOT of code, I can't use this technic for now.
Mainly because I need to read each batch (before serialize on disk) to get some information I need (for example, do I need to continue asking the server for a next batch ?)

For now, the benefits is not worth the investment to refactor everything, I guess.
That being said, I will keep in mind this improvement for a next future release !

**Comment by Mimetis** [comment]
Hey @gentledepp, I will close this issue, but still, it's tagged enhancement and investigation
