### ISSUE TITLE
Azure, 230 second limit

### ISSUE THREAD

**Issue by Tuytje** [Mimetis/Dotmim.Sync#474]
As you might know Azure has a 230 second limit for webrequest, which can't be changed.

Since I will be running this code on an Azure server I need to make sure that all requests are handled within that 230 second period, eventhough this might make the whole process longer. Because of this I have a couple of question to know if it could aid in making sure the 230 limit is not hit.

Is there anything we can do on the server database that speeds things up? 
Does the batch size on the server matter in speeding up the request time, or does it only matter for the time needed for the whole process?
Same question for the client.

I was able to time out the server in my tests by sending a lot of client changes, which is a situation that could realistically happen when a user is offline for some period (and can't sync as a result). Does the client batch size matter for this situation?

I have been testing on a test server (duh :)) which is not the most powerful server in the world, far from it :) What would benefit the sync framework more: more power to the sql database, or more power for the webserver itself? As far as I understand the framework I think that the webserver itself is the bottleneck, correct? So upscaling the cpu it has available would speed up the sync.

Some tables will rarely change and I am supplying the clients with the current values. This means that initially these tables don't really need to sync. Is there any way to mark a record as the same as the server? 
I have noticed that when I extended my tests to contain those tables as well, the time it needed for that initial sync went up although it doesn't really need to sync anything. I figured that checking those table was the extra time needed (5 tables, +- 250 records combined)

I will be bringing the code up & running in a pool of around 8000 possible clients (it is opt-in) and am trying to keep the possibility of failure as low as possible :)

Thanks for the awesome work!

**Comment by VagueGit** [comment]
We planned on moving our users to an Azure SQL Database Pool, but I couldn't get DMS to run within the 230 second timeout on the Azure App Service. We have users with 20 years of their business history in their databases, so we might not be typical DMS users.

We moved to [another provider](https://www.everleap.com/) that runs Azure. Their web servers timeout after 10 minutes and DMS works fine for us.

**Comment by Tuytje** [comment]
@VagueGit thanks for the provider, they have a pretty good deal. Sadly I cannot move away from Azure at this point, although I bookmarked the provider you mentioned for later use :)

Because of the dependence on Azure, my questions still stand :/

**Comment by VagueGit** [comment]
The other issue we struck is that we had to allow 3 minutes for Azure to create a new SQL Database. I was told they aim for 60 secs to create a new database, but on hundreds of tests we found that number unreliable. This makes for slow startup for new users which we judged would cost us business. Elsewhere CREATE DATABASE completes in seconds.

Once you have a database then the bottleneck is the web server. Particularly ram.

DMS might be more Azure friendly for those porting existing users if there was a [snapshot](https://dotmimsync.readthedocs.io/Snapshot.html) equivalent for uploading user data. Something that ran as a web job might be good. Maybe web jobs would also be a solution for sync timeout?

**Comment by Mimetis** [comment]
Hi @VagueGit , @Tuytje ,

Here are some recommendations about performances.

## Where performances are important and where bottleneck can happen ?

90% Server, 10% Client... almost (even maybe 99%/01% :) )

Your **client**, in a sync typo, is, often, a device, a standalone database, used by one connection.
In such situation, there is almost no impact on performance on the client side.

One thing to do on the client side, if you are dealing with a lot of changes, rows, is to set a `BatchSize`.
Be careful, `BatchSize` is **approximatively** exprimed in **Kb**

So far a good value should always be between **1000** and **5000**.

Your **server** on the other hand, has to handle hundreds of clients sync, and the tips and tricks here can save your day, I guess.

## Snapshots

First of all, the most intensive CPU / Database work, is the **first** synchronization from a new client device.
Basically, the server needs to get all the rows to initialize a client.
Even more, if there is no filter for the devices, this work is done for every single client, while the rows to retrieve are basically the same !

So far, using snapshots is really powerful when dealing with client initialization.
Yes, it's more maintenance, and you have to generate a snapshot for each filtered clients, and schedule a snapshot every X days, but it's worth it, for sure.

If a snapshot exists, the client initialization is way faster, and the server work is reduced.

My advice: Create a snapshot every 1 or 2 weeks, from a console application, for example:

``` cs
private static async Task CreateSnapshotAsync()
{
    var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(serverDbName));

    var snapshotProgress = new SynchronousProgress<ProgressArgs>(pa =>
    {
        Console.ForegroundColor = ConsoleColor.Blue;
        Console.WriteLine($"{pa.PogressPercentageString}\t {pa.Message}");
        Console.ResetColor();
    });
    var snapshotDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "Snapshots");

    var options = new SyncOptions() { BatchSize = 1000, SnapshotsDirectory = snapshotDirectory };

    Console.WriteLine($"Creating snapshot ");

    var setup = new SyncSetup(allTables);
    var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, allTables);
    var stopwatch = Stopwatch.StartNew();

    await remoteOrchestrator.CreateSnapshotAsync(progress: snapshotProgress);
    stopwatch.Stop();

    var str = $"Snapshot created: {stopwatch.Elapsed.Minutes}:{stopwatch.Elapsed.Seconds}.{stopwatch.Elapsed.Milliseconds}";

    Console.WriteLine(str);
}
```

**Be Careful** : If you have a schema with filters, you **must** create a snapshot per filter value !

``` cs
Console.WriteLine($"Creating snapshot for each customer");

var setup = new SyncSetup(new string[] { "Customer" });
setup.Filters.Add("Customer", "CustomerID");

// creating a snapshot for each customerId (that is my filter)
for (int customerId = 1; customerId <= 10; customerId++)
{
    var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);
    var stopwatch = Stopwatch.StartNew();

    var parameters = new SyncParameters {
        { "CustomerID", customerId }
    };

    await remoteOrchestrator.CreateSnapshotAsync(syncParameters: parameters,
                                                    progress: snapshotProgress);
    stopwatch.Stop();
    var str = $"Snapshot for customer {customerId} created: {stopwatch.Elapsed.Minutes}:{stopwatch.Elapsed.Seconds}.{stopwatch.Elapsed.Milliseconds}";
    Console.WriteLine(str);
}

```

## Disable Constraints

To be sure you won't have a foreign key constraints raised during your sync, `DMS` disable all the constraints on the sync table, before making the sync, then enable them again, at the end.
The BIG problem with this technic is that, **once the constraint is disabled, the table is locked for the transaction**...
So, a second client that launches a synchronization, will have to wait until the first client has ended its own sync

IF you're confident with your database and you know you will never have a foreign key constraint raised when making a synchronization, you can disable this options
``` cs
var options = new SyncOptions { DisableConstraintsOnApplyChanges = false };
```
You'll see that the performance increase will be **huge** since any client will not have to wait another one to complete its sync...

**How to know if you need to enable / disable constraint ?**

Well, it really depends on your database schema.
Here is an example, where we **need to disable the constraints** to make the sync works correctly.
In the [AdventureWorks schema](https://raw.githubusercontent.com/Mimetis/Dotmim.Sync/master/CreateAdventureWorks.sql) we are using here for demo purpose, we have one table called **ProductCategory**.
This table has a foreign key **on itself** to references a *parent category*:

```sql
CREATE TABLE [dbo].[ProductCategory](
	[ProductCategoryID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ParentProductCategoryID] [int] NULL,
	[Name] [nvarchar](50) NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[ModifiedDate] [datetime] NOT NULL);

ALTER TABLE [dbo].[ProductCategory]  WITH CHECK 
ADD  CONSTRAINT [FK_ProductCategory_ProductCategoryID] 
FOREIGN KEY([ParentProductCategoryID])
REFERENCES [dbo].[ProductCategory] ([ProductCategoryID])

```
As you can see `ParentProductCategoryID` references `ProductCategoryID`.

Here is an extract of the rows we have with such constraints:

```
ProductCategoryID ParentProductCategoryID Name
----------------- ----------------------- --------------------------------------------------
1                 NULL                    Bikes
2                 NULL                    Components
3                 NULL                    Clothing
4                 NULL                    Accessories
5                 1                       Mountain Bikes
6                 1                       Road Bikes
7                 1                       Touring Bikes
8                 2                       Handlebars 
```
As you can see, **Mountain Bikes** category *belongs* to the **Bikes** category.

That being said, when making a sync, all the `insert / update / delete` **MUST** be ordered.
Indeed, we can't insert a category **before** inserting its parent: We can't insert **Mountain Bikes** if we have not inserted **Bikes** before.

Unfortunately, we can't get these lines ordered when `DMS` is making a `Select_Changes`. Not the fault of `DMS`, but the SQL engine will get the line in the most effective way, and not necessarily in the order we need.

Here is an output while trying to make a sync on the AdventureWorks sample with `DisableConstraintsOnApplyChanges = false`:

``` cs
0%:     857157dc-b71e-4802-85c3-2b2b2cd7d1ac:   Session Begins.
The INSERT statement conflicted with the REFERENCE constraint "FK_Product_ProductCategory_ProductCategoryID". The conflict occurred in database "Client", table "dbo.Product", column 'ProductCategoryID'.
The statement has been terminated
```

### How to mitigate this disable / enable constraints

The `DisableConstraintsOnApplyChanges` is **global** to the schema, for **all** tables. 
But what can we do if we know we have the problem with only **1 or 2** tables ?

Well, you can use the interceptors `OnDatabaseChangesApplying` and `OnDatabaseChangesApplied`
These 2 interceptors are raised before and after all the `insert / update / delete`

So far, dealing with the `ProductCategory` problem, can be handled like this:

``` cs
orchestrator.OnDatabaseChangesApplying(args =>
{
    var command = args.Connection.CreateCommand();
    command.Connection = args.Connection;
    command.Transaction = args.Transaction;
    command.CommandText = "ALTER TABLE [ProductCategory] NOCHECK CONSTRAINT ALL";
    return command.ExecuteNonQueryAsync();
});

orchestrator.OnDatabaseChangesApplied(args =>
{
    var command = args.Connection.CreateCommand();
    command.Connection = args.Connection;
    command.Transaction = args.Transaction;
    command.CommandText = "ALTER TABLE [ProductCategory] CHECK CONSTRAINT ALL";
    return command.ExecuteNonQueryAsync();
});
```

## Indexes

Make a survey on your database to see how you can improve the performances, by setting the correct indexes.
`DMS` had some indexes, but you know your database better then me, so creating some good indexes may be worth it !

## Anything else ?

Well if you have any idea, please make a comment, I will update this post, and then I will add it, as a page, in the official doc :)

**Comment by Mimetis** [comment]
Since there is no more comments, I guess we can close this issue ?

**Comment by Tuytje** [comment]
Yes, you can. Thank you for the feedback!

**Comment by VagueGit** [comment]
Pardon my adding to a closed issue but on the question of performance ... although you say 

> you know your database better then me, so creating some good indexes may be worth it

What makes a good index can be a moot point depending on your perspective/use case. What are important indexes for DMS? Foreign key indexes, I suppose?

**Comment by Mimetis** [comment]
`DMS` creates its own indexes for tracking tables
For your tables, it's up to you !
