### ISSUE TITLE
system.data.sqlite not supported

### ISSUE THREAD

**Issue by abunoman2003** [Mimetis/Dotmim.Sync#49]
It is possible to include system.data.sqlite as SqliteSynchProvider? So that can use sqlite database version 3 and password.
Thanks

**Comment by Mimetis** [comment]
I use the `Microsoft.Data.Sqlite` nuget package, and not the `System.Data.Sqlite` package, since it's not `.Net Standard` yet.

`Microsoft.Data.Sqlite` does not supports keywords like `Password` or `Version` in connection string.
Those keys are parsed by providers, often, and it's not related at all on `SQLite` engine.

If you want to implement an encrypted version, see those posts:
[https://www.bricelam.net/2016/06/13/sqlite-encryption.html](https://www.bricelam.net/2016/06/13/sqlite-encryption.html)

[https://github.com/aspnet/Microsoft.Data.Sqlite/blob/17e4cd22d7c43c721eb51925ab0864187fa3ffd0/samples/EncryptionSample/Program.cs](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/17e4cd22d7c43c721eb51925ab0864187fa3ffd0/samples/EncryptionSample/Program.cs)
