### ISSUE TITLE
Conflict with SQLconnector

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#492]
Due to bugs in Microsoft.Datal.mySQL, I absolutly need to use MySQLconnector.

If I create a serverProvider that way
```
Dim serverProvider As MySqlSyncProvider= New MySqlSyncProvider("mystring")
```
I get an error `Failed to import type 'MySqlConnectionStringBuilder' from assembly or module 'MySqlConnector.dll'`.

But this way is ok
```
Dim serverProvider As MySqlSyncProvider= New MySqlSyncProvider()
serverProvider.ConnectionString = "mystring"
```

Strange...

**Comment by Mimetis** [comment]
Yes, it's because there is a conflict version in `MySqlConnector`

Are you working with `.Net Core 3.1` or `.Net 5` ?

Is so, you can try with the prerelease `v0.7.0` that handles the conflict. (See https://github.com/Mimetis/Dotmim.Sync/discussions/489)


If you are inside a `.Net Standard 2.0`, u need to downgrade `MySqlConnector` to version `0.69.10`

**Comment by sylverbee** [comment]
I tried with MySQLconnector 0.69.10 but it's worth!
So I removed MySQLconnector and will try to find another path.

**Comment by Mimetis** [comment]
I've already done several samples using MySqlConnector and it's working actually.
But if you find a better way, that's good I guess :)
