### ISSUE TITLE
args.Table.Rows.Count in OnTableChangesApplying is always 0

### ISSUE THREAD

**Issue by andreasfromch** [Mimetis/Dotmim.Sync#524]
Hi,

I’ve a problem with OnTableChangesApplying. Either I’m using it the wrong way or there is misunderstanding a from my side.
I’ve a MSSQL database on the server on a WinForms Program with SQLite on the client (Version v0.7.4-beta-0616). If I delete a record direct on the SQL server and update one record as well on the server OnTableChangesApplying is called two times but the count variable is always 0 as you can see in the attached screenshots. If I only delete one record OnTableChangesApplying isn’t even called.
Do you have any suggestions what I can do or what I’m currently doing wrong?
Or is there any kind of problem known?

Any help is appreciated.

Regards,

Andreas

![Modified](https://user-images.githubusercontent.com/30843010/113504756-67613e00-953a-11eb-8824-18bf8246dfb8.png)
![Deleted](https://user-images.githubusercontent.com/30843010/113504758-692b0180-953a-11eb-9f79-9372583dcd31.png)

**Comment by Mimetis** [comment]
Yes, `OnTableChangesApplying` is raised at the very begining. The `SyncTable` property has only the name of the table.

If you want the rows count to be applied for each table, you need to use `OnTableChangesBatchApplying` 
You will have the rows count for the current batch to be applied (and you will be able to change the rows if you need)
Be careful, you will have rows for each batch, no the whole table.

You can test also `OnTableChangesBatchApplied` where you will have the result of the current batch applied.

Then you can test the `OnTableChangesApplied` where you will have the result of the rows applied for the current table (and then the rows count)

**Comment by andreasfromch** [comment]
Thanks a lot for the clarification.

After modifying one record and delete an other I get the modified one in OnTableChangesBatchApplying as mentioned by you but not the deleted one.
Is it possible to get the delete one as well on any way or at least the primary key of it?

**Comment by Mimetis** [comment]
I have them

![image](https://user-images.githubusercontent.com/4592555/113775754-7528e600-9729-11eb-80ed-62700c04ba95.png)

**Comment by andreasfromch** [comment]
Thanks, I’ll do some testing with my application and try to isolate the problem. If I have any new Information I’ll come back.

**Comment by andreasfromch** [comment]
I did some testing with my application and currently it seems for me that that problem occurs if I use filters. I’ll try to reproduce it with the HelloWebSync sample.

**Comment by andreasfromch** [comment]
So, I was able to break it down to a very simple example. I’ve used your “HelloWebSync” sample and cut it down to an absolute minimum. If I user a filter (I know it makes not much sense but is good enough for showing the problem) I only get modifications an no deletes in “OnTableChangesBatchApplying”. If I did something wrong or misunderstood anything please let me know.

![Client](https://user-images.githubusercontent.com/30843010/115058767-dd27bb00-9ee5-11eb-8c13-9b1afdced16b.png)

![Server](https://user-images.githubusercontent.com/30843010/115058788-e0bb4200-9ee5-11eb-8887-83140d5797cf.png)

**Comment by Mimetis** [comment]
Hello @andreasfromch 

_Before going a little bit deeper into your problem one suggestion: Please **do not** use Screenshots for sharing your code.
It's **WAY better** to share your code with Markdown, as I will do in this entire post.
It's simplest for everyone, just because we can copy / paste the code (something we can't do with screenshots ;))_

That being said, here is an explanation of your bug.

Using the `CustomWhere` method allows you to do "_whatever you want_" with the `Where` clause in the select changes.
For instance, here is the code that is generating when using your code:

``` cs
var filter = new SetupFilter("SalesOrderDetail");
filter.AddParameter("OrderQty", System.Data.DbType.Int16);
filter.AddCustomWhere("OrderQty = @OrderQty");
```

``` sql
SELECT DISTINCT ..............
WHERE (
(
  OrderQty = @OrderQty
)
AND 
	[side].[timestamp] > @sync_min_timestamp
	AND ([side].[update_scope_id] <> @sync_scope_id OR [side].[update_scope_id] IS NULL)
)
```
The problem here is pretty simple. When you are deleting a row, the tracking table marks the row as deleted (`sync_row_is_tombstone = 1`)
And of course the row is not existing anymore in the `SalesOrderDetail` table.
And as you may expect, the deleted row will never been selected for sync, because of your `where` clause ...

Fortunately for us, we have two solutions as workaround.
The first one is the most simplest, since you are using **an existing column to filter**, we can use an integrated method of `DMS` that will generate the right statement:

``` cs
var setup = new SyncSetup(tables);

//var filter = new SetupFilter("SalesOrderDetail");
//filter.AddParameter("OrderQty", System.Data.DbType.Int16);
//filter.AddCustomWhere("OrderQty = @OrderQty");
//setup.Filters.Add(filter);

setup.Filters.Add("SalesOrderDetail", "OrderQty");
```

Using this _out of the box_ method (and because we are filtering on a table column), we can use the `setup.Filters.Add(TableName, ColumnName)` method.

This method will generate this sql statement:

``` sql
SELECT DISTINCT ....
WHERE (
(
 (
   ([base].[OrderQty] = @OrderQty)
  )
 OR [side].[sync_row_is_tombstone] = 1
)
```
As you can see, we have a clause bind to `sync_row_is_tombstone`. This is why, with this clause, the row deleted will be selected.

The second method is just to generate the correct sql with the `AddCustomWhere` method.
But honestly, if your filter IS a column of your table, I think you should not use the `AddCustomWhere` method, since it's too permissive.

``` cs
var filter = new SetupFilter("SalesOrderDetail");
filter.AddParameter("OrderQty", System.Data.DbType.Int16);
filter.AddCustomWhere("OrderQty = @OrderQty OR side.sync_row_is_tombstone = 1");
setup.Filters.Add(filter);
```

**Comment by andreasfromch** [comment]
Hi @Mimetis
Sorry for the screenshots 😉! If I have anything else, I’ll just copy/paste code 😊.
Thanks a lot for the time you took for analyzing my problem and explain to me! This is a much better support than you can get for many commercial software companies.
Now it’s very clear for me. I’ll use your second example because in my real application I’ve a subselect to get the field from another table with two parameters and one constant combined with AND an OR.
I realy love your project 😊!
