### ISSUE TITLE
Something wrong with the ChangeTracking sync feature

### ISSUE THREAD

**Issue by IsmailHassani** [Mimetis/Dotmim.Sync#667]
When using the **change tracking** sync feature,  I get every time the exception that the "_tracking" table is not found.
This is probably because the ```SqlSyncChangeTrackingProvider``` inherits from the ```SqlSyncProvider```.
In this provider the method ```GetParsers``` checks for this table which in this configuration does not exist. 
Am I missing something here?

**Comment by Mimetis** [comment]
Can make a sample repro ?

**Comment by IsmailHassani** [comment]
@
> Can make a sample repro ?

I'll try to create a simple one.

**Comment by Mimetis** [comment]
Otherwise, try to Deprovision / Provision your database
Maybe you've done some tests and the metadatas are not up to date with the correct provider

Or try with a fresh database (server / client) and see if it's working

**Comment by IsmailHassani** [comment]
@Mimetis Already done this. I also created a fork of the repo to see the inner details and noticed this GetParsers method is also called in the ChangeTracking version. And this is causing this check and the error.

**Comment by Mimetis** [comment]
Indeed, can be potentially here, since this method is static.
Are you able to make a quick repo ?

**Comment by IsmailHassani** [comment]
Ok, i managed to create a demo repo.
As long it uses the non-tracking feature it works.
But after using the changetracking i get the missing _tracking exception.

 Repo: [Github](https://github.com/IsmailHassani/SyncDemo)

**Comment by kevindost** [comment]
https://github.com/IsmailHassani/SyncDemo/blob/b66df53e34d8326198eea4cd258cc699fc231c92/SyncDemoClient/Services/SynchronizationService.cs#L137

There is a call to UpdateUntrackedRowsAsync which is not meant for the SqlSyncChangeTrackingProvider

**Comment by IsmailHassani** [comment]
@kevindost i missed that one. 😮

**Comment by Mimetis** [comment]
Good catch @kevindost !

Indeed, the `UpdateUntrackedRowsAsync`  can't work with change tracking.
I guess, we may need to raise an explicit error for this one, since we can't update untracked rows, when use the `SqlSyncChangeTrackingProvider`.

@IsmailHassani let us know if it's resolving your issue

**Comment by IsmailHassani** [comment]
@Mimetis and @kevindost 
After removing this line the error is gone.
However, the tracking tables are still generated. This is probably due the fact it inherits from the sql provider.
Also the database is not synced at all.
Am I missing another step?

**Comment by Mimetis** [comment]
Did you restart from a fresh server database without any sync metadatas in place ?

**Comment by IsmailHassani** [comment]
@Mimetis 
I will clean everything and try again to be sure.

**Comment by IsmailHassani** [comment]
@Mimetis Even with 2 new databases the same result. 
The tracking tables are added and synchronization of existing records (or after updates) are not reflected to the new DBSync table.

**Comment by IsmailHassani** [comment]
@Mimetis Even with 2 new databases the same result. The tracking tables are added and synchronization of existing records (oafer updates) are not.
I updated my repo and added the actual database i'm trying to sync.

**Comment by Mimetis** [comment]
Starting from your sample, I've done some minor changes:

Restore your backup.
You still have in it a table called `sync_scope` that I removed (it contained a schema with `SqlSyncProvider` that should not exists here)
`sync_scope` table is only created on the client side.

So far it should not exist on the server side, and we are trying to start from a fresh new server database.

In the `ClientSynchronizationOptions.json`, I've replaced the connection string with my client database (called Client)

``` json
{
  "Channel": "SyncGroup",
  "CheckHostInterval": "00:00:05",
  "Host": "https://localhost:44351",
  "IsMaster": true,
  "ConnectionString": "Server=(Localdb)\\MSSQLLocalDB;Database=Client;Trusted_Connection=True;MultipleActiveResultSets=False"
}
```
I removed `await agent.LocalOrchestrator.UpdateUntrackedRowsAsync()` in `SynchronizationService.cs`

By the way you are doing a **Deprovision** / **Provision** on every sync
It's not performant at all, since this mechanism should be called only on the first call (not every calls) and it's done automatically by `DMS` on the first sync
It should be used only when you have a de-sync situation, like upgrade, bug, un-sync or any weird situation

So far, I remove a lot of code (I don't understand what is `_options.IsMaster` but you do 2 syncs in a row, and it not necessary)

``` cs
 var serverOrchestrator = new WebClientOrchestrator($"{_options.Host}/api/sync");
 var clientProvider = new SqlSyncChangeTrackingProvider(_options.ConnectionString);

 var options = new SyncOptions
 {
     BatchSize = 1000,
     DisableConstraintsOnApplyChanges = true
 };

 // Creating an agent that will handle all the process
 var agent = new SyncAgent(clientProvider, serverOrchestrator, options);

 // await agent.LocalOrchestrator.DeprovisionAsync();

 // var schema = await serverOrchestrator.GetSchemaAsync();

 // await agent.LocalOrchestrator.ProvisionAsync(schema, true);

 // Launch the sync process
 // This first sync will create all the sync architecture
 // and will get the server rows
 await agent.SynchronizeAsync();

 if (_options.IsMaster)
 {
     // Now we can "mark" original clients rows as "to be uploaded"
     //await agent.LocalOrchestrator.UpdateUntrackedRowsAsync();

     // Then we can make a new synchronize to upload these rows to server
     // Launch the sync process
     //await agent.SynchronizeAsync();
 }

```

And it worked correctly

Client side :

![image](https://user-images.githubusercontent.com/4592555/146970600-017c0e86-ae3e-4bc8-bc94-1b493d2b7665.png)

As you can see here, we have a `sync_scope` table only (no tracking tables)

Server side:

![image](https://user-images.githubusercontent.com/4592555/146970887-4892e8f0-0bee-4d04-a278-9d84bf4337dc.png)

As you can see here, we have a `scope_info_history` table and a `scope_info_server` table only (no tracking tables)

**Comment by IsmailHassani** [comment]
Ok, I managed to get it to work. Thank you for your explanation.

But I still have some questions, because in my mind I had it all the other way around.
- The server has the main database and is synced to the clients. But what if want to this the other way around? 
Because I have multiple clients (only download) and one master client (only uploads, hence IsMaster) and the server database with the related tables. I got it working with the regular sqlprovider only had some issues with the autonumbering of index fields (integers).
- What if the client already has a database with data inside it. Will this data be deleted or removed?
- How to force the initial data to be pushed to the server? or is this scenario not possible with change tracking?

Thank you in advance.
;)

**Comment by Mimetis** [comment]
> The server has the main database and is synced to the clients. But what if want to this the other way around?
Because I have multiple clients (only download) and one master client (only uploads, hence IsMaster) and the server database with the related tables.

You can't have a database with both role : you can't be a **client** at one time, and becoming a **server** after.

The sync typology is always
- **1** server
- **1-N** clients

![image](https://user-images.githubusercontent.com/4592555/147272785-bf0b3ec9-87a8-4d62-b90b-8e4c3a38704c.png)

>  I got it working with the regular sqlprovider only had some issues with the autonumbering of index fields (integers).

https://github.com/Mimetis/Dotmim.Sync/issues/590

> What if the client already has a database with data inside it. Will this data be deleted or removed?

The rows are still available on client. If you want to upload them to the server, you have to use the `UpdateUntrackedRowsAsync` method.
This method will work only if you are using the `SqlSyncProvider`. It won't work with `SqlSyncChangeTrackingProvider`.

> How to force the initial data to be pushed to the server? or is this scenario not possible with change tracking?

See previous comment on `UpdateUntrackedRowsAsync`

**Comment by IsmailHassani** [comment]
Thank you for the clear explanation.
