### ISSUE TITLE
Incredible loop counts

### ISSUE THREAD

**Issue by JiriOgurek** [Mimetis/Dotmim.Sync#675]
My sync process (client --> server, upload only) of about 10.000 records (in 17 tables) takes 1-2 secs. However when I insert these same 10.000 records manually and I run sync again, it's running 350 secs instead of 2 secs, when I take a look inside using the profiler the main trouble is that some loops are performed more than 32 million times! In fact it's even more, because I stopped it earlier before it's been finished. What's wrong, please?

![image](https://user-images.githubusercontent.com/49657334/148213141-0f0b57c9-5b91-40f2-ae4c-04dbaf2bf174.png)

**Comment by Mimetis** [comment]
Because you have conflicts.
I assume you are inserting the same rows again.
Try to insert 10000 New records, and test

**Comment by JiriOgurek** [comment]
Yes, you are right, as I wrote above, I am inserting the same values. But why it takes so long, please? I would expect some kind of upsert or skip job, I see no reason why it takes so extremely long.

**Comment by Mimetis** [comment]
Because you have conflicts.
I guess server and clients have the same rows updated before you are making the sync ?

**Comment by JiriOgurek** [comment]
Yes, but how can 10.000 records fire up hardcore CPU benchmark using incredible (million) loops lasting more than 5 minutes, when it can skip or upsert, when it's same...? Thank you for your explanation.

**Comment by Mimetis** [comment]
How a conflict is raised:

Let's see what happens on a row with `ProductId = A001` and let's say `ProductName= Bikes`
This row is already sync on each device (let's say we already made a first sync, where everything was successfully synced)

Now:

#### Classic Server update : No conflict:

- Server makes an Update and row is changed to `A001` /  `Bikes-S`
- Sync
- Client Gets update on `A001` /  `Bikes-S`

#### Classic Client update : No conflict:

- Client makes an Update and row is changed to `A001` /  `Bikes-C`
- Sync
- Server Gets update on `A001` with  `Bikes-C`

#### Update Conflict

- Client makes an Update on row and changed to  `A001` / `Bickes-X`
- Server makes an Update on row and changed to  `A001` / `Bickes-Y`
- Sync
- Conflict is raised because we don't know which one is the correct value
  - Let's say that **Conflict Resolution** is set to `ServerWins` (default value)
    - Nothing changes on the server (Server wins the conflict, the row will not change)
    - Client will make a force update on its row to get the correct value `A001` / `Bickes-Y` from the server

Now you see if you have **10000** conflicting rows you will have **10000** forced update on the client.

More on that, if you are registering the event `OnApplyChangesFailed`, **DMS** will fetch the 2 rows in conflicts to let you see what is the differences and see what is the good solution to apply (overriding the Client Resolution property)
So far, 10000 more select to get each row in conflicts

#### GetRowByPrimaryKeys

That been said, it's not normal to have millions of call to `GetRowByPrimaryKeys`
This method is called for each row in conflict, on both side
So far, if you have 10000 conflicts, this method is called 10000 for the server side, and 10000 for the client side

#### Millions ?

> Yes, but how can 10.000 records fire up hardcore CPU benchmark using incredible (million) loops lasting more than 5 minutes

**That's not normal, can you make a repro sample ?**

> when it can skip or upsert, when it's same...? Is it possible to avoid this benchmark and force sync to skip or upsert, please

We know we have an update, but we don't know if the value have changed and is the same on each side
How can we know ? We stille need to make at least a select to compare....

- Client makes an Update on row and changed to  `A001` / `Bickes-U`
- Server makes an Update on row and changed to  `A001` / `Bickes-U`
- Sync
- Conflict is raised (and you know the conclusion)

Makes sense ?

**Comment by JiriOgurek** [comment]
Millions? Sure, can you see screenshot above? This is 10.000 records sample... Repro sample? Sure, I can do so with every manual insert on server side. I do understand your conflict scenarios, but none of them is mine. What I am facing is (UploadOnly) scenario, when client inserts new records and server gets exactly the same records manually (from other source than from sync mechanism):
- Client makes an Insert and inserts A001 / Bickes-U
- Server makes an Insert and inserts A001 / Bickes-U
- Sync - and we are facing benchmark test

If I understand right, the framework detects there's already A001 row, but doen't know if it's same. So my questions are:
1) why this scenario triggers benchmark - why there are million loop counts?
2) how can I force the update (even if it's same) or abort/skip of this ID?

Thank you for your kind help.

**Comment by Mimetis** [comment]
I've just made an update on the source code to improve your scenario:

To able to test it, you should:
- Make the test from the source code (and not from the package from nuget) Make a clone locally and add the csproj to your solution
- Make sure you are testing from a new fresh database. This update implies to modify some stored procedures.

Let me know if it is improving something.

On your scenario, if resolution is set to `ServerWins`, you should not have anything happening on the server (since `DMS` makes the conclusion that for each conflicting rows, the server has the good version)

But the row will be sent back to the client to be forced applied.
 
Let me know if you have better performances on the server side with this patched version

But once again, you should AVOID any conflicts, the most as possible, when you are making a sync mechanism.
Conflicts are a performance bottleneck for any database.

Let me know

**Comment by JiriOgurek** [comment]
YES, it works like a charm! Thank you very much :-)

**Comment by Mimetis** [comment]
Nice
