### ISSUE TITLE
Command timeout and execution time of stored procedure bulkupdate

### ISSUE THREAD

**Issue by ReinholdGuenter** [Mimetis/Dotmim.Sync#697]
When I initially sync a large database, I usually get command timeouts for the largest tables.
After I compiled DMS myself and increased the command timeout, I could figure out, that the execution time of the stored procedure bulkupdate can be up to minutes.
The execution time varies for the same table from seconds up to 12 minutes.

The sync is done with a BatchSize of 10 * 1024. The affected tables have up to 7 million rows.
I used a local MS SQL server and MS SQL and Azure as remote DB servers.

Does somebody have an explanation for theses huge variations in execution time?
Could the command timeout be added to the SyncOptions, so it can be increased if necessary?

**Comment by Mimetis** [comment]
When it takes 12 minutes, it's most probably because you have conflicts that should be resolved on both side
Try to see if you have conflicts raised when you have the 12 minutes sync issue.

**Comment by ReinholdGuenter** [comment]
No, I don't see any conflicts. It happens during the initial sync, when one database has no data at all. So there should not be any conflicts possible.

Here is the section from my log:
[SyncLog.txt](https://github.com/Mimetis/Dotmim.Sync/files/8089409/SyncLog.txt)

**Comment by Mimetis** [comment]
- Are you using the last version ?
- Can you try to add `MultipleActiveResultSets=True;` to your connectionstring ?

**Comment by VagueGit** [comment]
Also @ReinholdGuenter you are probably aware that if you are using MS SQL on Azure you can adjust the timeout, but if you are using Azure SQL Database timeout is limited to 230 seconds.

**Comment by ReinholdGuenter** [comment]
Thank you for the suggestions.
I added `MultipleActiveResultSets=True;` to my connection string and a first test did not have these extreme execution times.
I will run multiple tests over the weekend and give you more feedback on monday.

**Comment by srupprecht** [comment]
I stumbled upon the same problem. I am trying to sync a table with 9,5 million rows and approx. 2 GB size to Azure Managed Instance and Azure SQL Database. I haven't been successful so far, always running into a timeout exception after a couple of million rows, even with `MultipleActiveResultSets=True`: 

_Table d_mda_state: Applying changes from 8551 files. 9540671 rows.
Unhandled exception. Dotmim.Sync.SyncException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding._ 

Syncing the same table to another on-prem SQL Server works like a charm and finishes without any problem. 

I noticed that the transaction log gets rather big. In my test case it increases to about 20 GB maximum, which is ten times the table size. I don't know if that might trigger a timeout under certain conditions.

The whole sync is encapsulated in one database transaction and everything is rolls back completely. Would it be possible to recover from a failed BulkUpdate and continue the initial sync without a complete restart?

**Comment by ReinholdGuenter** [comment]
Adding `MultipleActiveResultSets=True;` to the connection string did not solve the problem.
I received command timeouts in most of my synchronizations.

**Comment by Mimetis** [comment]
Is it working on a local sql server ?
Just to know if it's working without a timeout expiration due to Azure ?

**Comment by srupprecht** [comment]
> Is it working on a local sql server ? Just to know if it's working without a timeout expiration due to Azure ?

I don't have any problems with local sql server, only on Azure. So it is not a Dotmim.Sync problem.

Adding a `CommandTimeout` to the SyncOptions might be the easiest way to address this issue.

**Comment by Mimetis** [comment]
You have doc about timeout here : https://dotmimsync.readthedocs.io/Timeout.html

Unfortunately I'm not sure we can improve the command timeout on Azure

**Comment by Mimetis** [comment]
The your problem is mostly the first sync.
I guess the snapshot does not help here ?

If this is the case, can we imagine a procedure where you are replicating a backup to your client, with initial rows and make a sync from that point ?

**Comment by ReinholdGuenter** [comment]
Yes, the first sync is our main concern right now.
No, so far, snapshots did not help. But I have to test them in more detail with v0.9.3.

Such a procedure would be a good solution for my use case.
Something like a provision step with sync meta data initiation.

**Comment by Mimetis** [comment]
I'm working on it.
It's something feasible; but you will have to be very careful  with it :)
I'm currently testing it. Will update you asap

**Comment by Mimetis** [comment]
I have added a new method on the last commit called `SetSynchronizedAsync`

``` cs
await agent.SetSynchronizedAsync(progress: localProgress);
```

Basically, this method will mark your database as _synchronized_ when this method is called.
That mean, no rows from the server (from 0 to the time of call to this method) will be downloaded on next call to `SynchronizeAsync()`

The purpose of it is to let you:
- Make a server backup (without any sync metadata like triggers / stored proc / tracking tables)
- Restore the database on your client.
- Call the `SetSynchronizedAsync` to mark the local database as **already** synchronized (and create all the required infrastructure like triggers, tracking tables and so on ...

On the next call to `SynchronizeAsync`, only rows _added / deleted / updated_ from the server that has been created after call to `SetSynchronizedAsync` will be downloaded

Theorically, everything is pretty simple here, if you don't have any rows _updated_ / _inserted_ / _deleted_ on your server database, between your backup and now...

What happens to all rows that will be _updated_ / _inserted_ / _deleted_ **after** the backup is done ?
Well they will not be downloaded if you call (after restoring the backup) `SetSynchronizedAsync` on the local database.

This is where hard things are coming :)

What you can do is to specify the server timestamp (instead of letting the `SetSynchronizedAsync` do it)

Basically, this value means : 
- Give me the timestamp that will be the lower bound to get rows from server
- If this value is 0 I will get all the data from the server
- If this value is MAX_VALUE_FROM_SERVER, that mean I will get nothing from the server.

That's being said, you can do something like:
- Get the server timestamp
- Make the backup
- Restore database on client
- Call the `SetSynchronizedAsync` with the correct timestamp value
- Call `SynchronizeAsync` to get the rows between backup and now

Here is a macro sample:

``` cs
var agent = new SyncAgent(clientProvider, new WebClientOrchestrator(serviceUri), options);

var remoteTimestamp = await agent.RemoteOrchestrator.GetLocalTimestampAsync();

await MakeRemoteDatabaseBackupAsync() // make your server backup

await MakeLocalRestoreDatabaseAsync() // make a restore locally

// Mark si new local database as synchronized
await agent.SetSynchronizedAsync(remoteClientTimestamp:remoteTimestamp, progress: localProgress);

// make a synchronization to get all rows between backup and now
var s = await agent.SynchronizeAsync(localProgress);

Console.WriteLine(s);

```
Is that make sense ?

The code is on the master branch, and will be available on next version `v0.9.4`

**Comment by ReinholdGuenter** [comment]
Thank you very much. That sounds exactly like the feature, we are looking for.
I will test the changes and give you feedback.

**Comment by ReinholdGuenter** [comment]
I tested the feature with several databases and so far it works like a charm.

**Comment by Mimetis** [comment]
Oh really ? Wow that's good !
Any feedback on how to improve it ?
Do you feel more confident of using this backup technic in place of the snapshot technic ?

**Comment by ReinholdGuenter** [comment]
After the SetSynchronizedAsync the local database contains the `scope_info` tables from both, the local and remote database.
I guess, the remote tables `scope_info_history` and `scope_info_server` could be removed afterwards.

In my tests, the workflow of creating the snapshot and synchronize using it was slower.
Creating and restoring backups is also used in our current workflows, so we are more familiar with it.
Our biggest fear are corrupted databases. The backup technic seems to give us the possibility of a clean start and more freedom.

**Comment by Mimetis** [comment]
Indeed scope_info_history  and scope_info_server are only used on the remote (server) side.
As I said, you should backup your server database without the `DMS `metadata (triggers, stored proc, tvp, tracking tables, scope tables)

I prefer to say "remove all `DMS `metadata", but If you want to be more granular, you can keep:
- Triggers if you are using the same provider on both side
- Stored Procedures & TVP if you are using the same provider on both side
- - Tracking tables if they are empty and you are using the same provider on both side
You must remove:
- Scopes tables
- Tracking tables if they are not empty

As I said "remove everything from `DMS`" is easier I guess :)

**Comment by ReinholdGuenter** [comment]
Thank you for the clarification.

I got one more idea, that might help with such spontaneous exceptions, like command timeouts or connection problems.
Would it be possible, to make a synchronization with a target timestamp to limit the amount of data, that will be synchronized?
`last client sync timestamp < target timestamp <= current remote server timestamp`

That way, a synchronization could be segmented and the size of each synchronization step would be limited.
So if a spontaneous exception occurs, the amount of data, that has to be synced again, would be smaller.
