### ISSUE TITLE
Just saying ... v0.95 is almost v1 !

### ISSUE THREAD

**Issue by Mimetis** [Mimetis/Dotmim.Sync#758]
Most probably, the `v0.95` will become `v1` when all the bugs will be resolved.

Please:
- Test the new version as it's a major one : Have a look here : https://github.com/Mimetis/Dotmim.Sync/discussions/755
- Please let me know here if you think some features (important) are missing

Will it change something ? 

No

Still an OSS project without any guarantee nor support, a part from what I humanly can do

**Comment by champcbg** [comment]
This is awesome product.  I was using with several past xamarin apps.  On a new project I trying Microsoft.Datasync, it was horrible experience because the error handling was lacking.  And the Push/Pull process was a black box with no way to get the logs.

What was good was that it hide, I believe the who creating and migrating DB's to the latest entity versions.  

That being said, I switched back to dotmin.sync

**Comment by Vextamour** [comment]
> This is awesome product. I was using with several past xamarin apps. On a new project I trying Microsoft.Datasync, it was horrible experience because the error handling was lacking. And the Push/Pull process was a black box with no way to get the logs.
> 
> What was good was that it hide, I believe the who creating and migrating DB's to the latest entity versions.
> 
> That being said, I switched back to dotmin.sync

This is great feedback on Microsoft.Datasync because I was going to check this out as well. Thanks for commenting this!

**Comment by champcbg** [comment]
It uses ODATA as the primary transport.  Im not a big fan of ODATA, it forces all clients to implement rules and the API is just a CRUD repo.

One of the things I did like on the client side it used different base class for entities, so i had client entities and server entities.  Where with Dotmim, Could share my entities and have base context class that inherited for SQL and SQLite.  A complete minimization and simplification of DbContext and Repo because of the sharing I could do. 

Any articles you create I would be honored to share my strategy on implementation

**Comment by Mimetis** [comment]
Interesting.
Would be Interesting to have à comparaison between both solution... Implémentation, performances, features...

**Comment by champcbg** [comment]
What I found is the client would pull the records from the server, but would never store in the local store.  

I would do a pull, which pulled records the server to client, that was suppose to store them locally.  But when I went to query the local table 0 (zero) records where found.

Unlike dotmin, there was not enough logging to figure out what was the issue.
