### ISSUE TITLE
Workflow if Table or Column is added

### ISSUE THREAD

**Issue by BluePalmTree** [Mimetis/Dotmim.Sync#796]
Hi,
first of all I really like the project, it works really well. 
This is more a question to clarify for me which steps are needed when the sync setup changes.

- We use version 0.9.1
- Server and Client are SQL Server
- Both use ChangeTracking 
- We use the WebProxy

# Table is added
When a new table is added that should be synced the table is added to the scope setup. The ASP.NET is restartet and the client automatically adds the new table to the sync.

### Questions

1. Is this correct or do we need to deprovision and provision?

# Column is added to table
When a new column is added to a table that is already tracked, we have to first deprovision than provision the scope schema. For this we have added to endpoints to the SyncController.
### Questions

1. Is this the same when a column is renamed (Is this a good idea or should be avoided when possible)
2. Is this the same when a column type is changed

## Server
```c#
[HttpGet("Provision/{scopeName}/{syncProvision}")]
public async Task<ObjectResult> Provision(string scopeName, int syncProvision = 4)
{	
	try
	{
		var orchestrator = orchestrators.FirstOrDefault(c => c.ScopeName.ToLower() == scopeName.ToLower());

		var result = await orchestrator.ProvisionAsync((SyncProvision)syncProvision);

		return Ok(scopeName);
	}
	catch (Exception ex)
	{
		return BadRequest(ex);            
	}
}

[HttpGet("Deprovision/{scopeName}/{syncProvision}")]
public async Task<ObjectResult> Deprovision(string scopeName, int syncProvision = 4)
{	
	try
	{
		var orchestrator = orchestrators.FirstOrDefault(c => c.ScopeName.ToLower() == scopeName.ToLower());

		await orchestrator.DeprovisionAsync((SyncProvision)syncProvision);

		return Ok(scopeName);
	}
	catch (Exception ex)
	{
		return BadRequest(ex);
	}
}
```
### Questions
1. Should the deprovision be called **before** the sql changes are made or doesn't matter?
3. Is the deprovision needed or could we directly call provision
4. We use 36 (ServerScope & StoredProcedure) as the parameter for the deprovision/provision method. Is this too much or which SyncProvisions are needed in this case?

## Client
On the client side we have to get the schema and then provision it. At the moment we have testet two different ways to do this and both seem to work,

```c#
// Config Scope
var serverSchema = await _serverOrchestrator.GetSchemaAsync();
await _agentConfig.LocalOrchestrator.ProvisionAsync(serverSchema);

// Receipts Scope
var serverSchema = await _serverOrchestrator.GetSchemaAsync();
await _agentReceipts.LocalOrchestrator.DeprovisionAsync(serverSchema, SyncProvision.StoredProcedures | SyncProvision.ClientScope);
await _agentReceipts.LocalOrchestrator.ProvisionAsync(serverSchema);
```
### Questions

1. Which way is better/more correct to get the new schema for the client
2. Is there already a way to detect if the server schema has changed or do we have to implement that ourselves?
3. Maybe there is already an issue where somebody asked these questions or posted there own code. A link would be appreciated :)

# Questions

1. What is the workflow when the version is updatet in a already running environement?

Like I said, i really like the project. Keep up the amazing work

**Comment by Mimetis** [comment]
Hello @BluePalmTree 
Sorry for the delay.

The version 0.9.1 is pretty old now, and things have changed a lot in the last release 0.9.7

Did you have a look on the [migration documentation](https://dotmimsync.readthedocs.io/Provision.html#migrating-a-database-schema) ?

Here are some thoughts about your questions:

> Is this the same when a column is renamed (Is this a good idea or should be avoided when possible)
> Is this the same when a column type is changed

Depends if you are able to upgrade your clients at the same time.

If yes, you can rename a column, or even changing its type, no worry.
- Be sure to `DeprovisionAsync` stored procedures and triggers before renaming / changing types
- During that time, no one should be able to sync, and no one should be able to add / remove rows (since they are not tracked anymore)
- Once column is changed, call the `ProvisionAsync` again for stored procedures and triggers

If you can do everything in a single transaction (`DeprovisionAsync`, Change column, `ProvisionAsync`) it could minimize the impact, I guess.

But once again, from now, and until clients are migrated, the sync is broken

On client side, do the exact same steps : `DeprovisionAsync`, Change column, `ProvisionAsync`.

Honestly, I would prefer to make a smoother upgrade:
- Don't change your column
- Add a new one that allows null and will replace the column you wanted to change
- Allow all clients to continue to sync with the old colums, until they have migrated
- All upgraded clients to sync with the new added column without having any side effect with the old one

You have a full explanation here, using the [multi scopes migration](https://dotmimsync.readthedocs.io/Provision.html#multi-scopes-migration).

It will allow you to continue syncing old clients with a first scope (relying on the old column) and having migrated clients to sync with the new added column on a new scope.

> Which way is better/more correct to get the new schema for the client

I prefer to get the schema from the server side (especially if you are using different databases types, like SQL Server / SQLite)

``` cs
// Getting the scope from server and apply it locally
var sScopeInfo = await remoteOrchestrator.GetScopeInfoAsync("v1");
```

> Is there already a way to detect if the server schema has changed or do we have to implement that ourselves?

If scope has changed from the server side (scope contains setup (tables list) and schema (tables descriptions)) `DMS` will raise an error you can intercept with `OnConflictingSetup`

``` cs
agent.LocalOrchestrator.OnConflictingSetup(async args =>
{
    if (args.ServerScopeInfo != null)
    {
        args.ClientScopeInfo = await localOrchestrator.ProvisionAsync(args.ServerScopeInfo, overwrite: true);

        // this action will let the sync continue
        args.Action = ConflictingSetupAction.Continue;

        return;
    }
    // silentely abort sync
    args.Action = ConflictingSetupAction.Abort;

    // The Rollback Action will raise an error
    // args.Action = ConflictingSetupAction.Rollback;
    }
});
```

> What is the workflow when the version is updatet in a already running environement?

https://dotmimsync.readthedocs.io/Provision.html#migrating-a-database-schema

**Comment by Mimetis** [comment]
Is it good for you ?

**Comment by BluePalmTree** [comment]
Seems like we can work with this. But we don't have time at the moment to test this. If we have time to test this more thoroughly I will give feedback. 
I think the bigger problem we have is to implement a process on how to automatically deploy SQL changes to the clients when the server changed, but that has nothing to do with the syncing itself. 
Since we are still in the testing phase I hope we can upgrade to the latest version, before production starts.
Any idea when version 1.0.0 will be ready?

**Comment by Mimetis** [comment]
The current version is "almost" the final version. The `1.0.0` will be this one, stabilized with minors fixes if needed.
I'm just waiting for more feedback before releasing the `1.0.0`

If you are testing with the current version (at least `0.9.7`), you are good to go already
