### ISSUE TITLE
Disk usage on server

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#797]
We've had a query from our server manager. c:\windows\temp\DotmimSync, is using up 21GB of disk space. He wants to know if it is ok to delete the contents of that folder.

**Comment by Mimetis** [comment]
Yes, 
These files are used during sync.
Once a sync session is done, the file should be deleted.

`DMS` is deleting the files when the sync session is done, but sometimes, for some reason, the file is not deleted (because of lock, because of failure or any other reason)

You can delete the content regularly, but be careful with the last one (by date), maybe you have an in progress sync, using the last file.
