### ISSUE TITLE
SqliteSyncProvider not releasing file?

### ISSUE THREAD

**Issue by dev-rpichler** [Mimetis/Dotmim.Sync#827]
Hi,

Using Xamarin Forms (latest)
Sqlite - net - pcl (latest)
Dotmim 0.9.7

Problem:
I'm trying to create a db,  sync db then delete the db,  create a new one and sync again.
This results in a sqlite exception "readonly database" in the second sync.

After several attempts and debugging I suspect that something is still accessing the sqlite-db and therefore the error arises. I guess it is the SqliteSyncProvider  but I did not found a method to close explicitly the connection.
I close and dispose all other db-connections in my app and without the sync it seems to work.

Is this possible or do you think there could be another problem?
Thank you very much & thank you for this great framwork!
Kind regards,
Robert

**Comment by Mimetis** [comment]
This is by design, [see breaking change note for 6.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#connection-pool).

The SQLite provider now pools connections, improving connection speed significantly but keeping connections open. You can disable pooling by adding `Pooling=false` to the connection string or calling `SqliteConnection.ClearAllPools()` at the point where you want them to be closed.

**Comment by dev-rpichler** [comment]
Thank you very much!
I was aware of the method ClearAllPools, but unfortunately it seems like that it is not available in sqlite-net-pcl, I 'm currently using.

Therefore I 'm using now:
 SqliteConnectionStringBuilder sqliteConnection = new SqliteConnectionStringBuilder
            {
                DataSource = _localDbPath,
                Pooling = false
            };
            SqliteSyncProvider clientProvider = new SqliteSyncProvider(sqliteConnection);

as proposed as first solution.
Thanks again!
Kind regards,
Robert
