### ISSUE TITLE
[Question] - when items are tombstoned on server, they are deleted on client but remain in _tracking table

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#86]
Hi!

Doing our integration tests, we noticed:
1) syncing rows from the server to a client
2) then deleting the rows from the server...
3) and syncing with the client again
=> actually removes the rows from the client (good), but keeps the corresponding rows in the _tracking table

Now our question is: Will they eventually be deleted by dotmim.sync, or will they be kept there forever?

**Comment by Mimetis** [comment]
they will be kept forever, until I found a correct solution :)

**On the client side**
- Every tombstone row could be safely removed once the sync is over (and no error raised or whatever)

**On the server side**
- Every tombstone row could be safely removed once **ALL** clients has a up-to-date sync (or at least all clients has deleted the tombstones rows)

An approach to this issue is to follow the rules alread implemented in SQL Server:
- Add a method on the `Dotmim.Sync` (probably in the client `IProvider`) that will take a `datetime?` and will delete all the `_tracking` rows to this datetime.
- On Sql server, a sub-routine delete all metadatas rows after 14 days (so a client **HAS TO** sync at least once every 13 days :)

What do you think ?

**Comment by gentledepp** [comment]
I think the "cleint HAS TO sync every XY days" is the way to go.
However, I would be glad if we did not have to hard code it.

How would it be if:
1) in the SyncSettings you specify the maximum period that a client may not be connected
2) when a client syncs, it first checks whether it has not exceeded that period (e.g. 14 days by default)
  2a) in case it has not exceeded that period, it just syncs the data
  2b) in case it *has* exceeded that period, it automatically does a "ReinitializeWithUpload" sync
3) after a successful sync process, it cleans up the tracking tables (based on that period)

We actually follow this approach with the syncfilters as well. Whenever they get deleted, they will still be kept for a preconfigured duration (e.g. 14 days or 3 months) and then be deleted. In case the client has not synchronized for that long, it has to re-sync everything, so any rows that it may not be allowed to see anymore are deleted as well.

**Comment by Mimetis** [comment]
Resolved in the last version
