### ISSUE TITLE
Provision from local schema adds offset to DateTime data.

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#939]
Using DMS 0.9.8-beta-1056 with SQLite on client and SQL Server via Api
On the client we have a column defined as
`FooDate datetime COLLATE NOCASE, `
and on the server as
`[FooDate] [date]`
If we provision an existing local SQLite database like this
```
SyncSet syncSet = await localOrchestrator.GetSchemaAsync(syncSetup);

ScopeInfo scopeInfo = new ScopeInfo
{
    Name = scopeName,
    Schema = syncSet,
    Setup = syncSetup,
    Version = SyncVersion.Current.ToString()
};
await localOrchestrator.ProvisionAsync(scopeInfo);
```
When a change to FooDate is made on the server then synced to the client, FooDate appears on the client in the format YYYY-MM-DD HH:MM:SS + OFFSET

This can be difficult to handle as DateTime.

However if the client is provisioned using scopeInfo from the server like this
```
ScopeInfo scopeInfo = await syncAgent.RemoteOrchestrator.GetScopeInfoAsync(scopeName);
await syncAgent.LocalOrchestrator.ProvisionAsync(scopeInfo);
```
FooDate appears on the client without the offset in the format YYYY-MM-DD HH:MM:SS.

This is easier to handle as DateTime

**Comment by Mimetis** [comment]
Because your local scope is different from the server scope, as `FooDate datetime COLLATE NOCASE` is basically just a `[Text]` column and DMS sees the column as string, and then does not make the effort to convert the value from server.

When getting the scope from server, **DMS** saved the column as `Date` and then will make the effort to convert the text to date.
